<?php
namespace Database\Seeders;

use App\Models\ClaPresupuestario;

use Illuminate\Database\Seeder;

class ClaPresupuestarioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $institucion = [
            ['codigo'=>'11000','nombre'=>'INGRESOS DE OPERACIÓN','tipo'=>'R'],
['codigo'=>'11100','nombre'=>'Venta de Bienes','tipo'=>'R'],
['codigo'=>'11300','nombre'=>'Venta de Servicios','tipo'=>'R'],
['codigo'=>'11400','nombre'=>'Alquiler de Edificios y/o Equipos','tipo'=>'R'],
['codigo'=>'11500','nombre'=>'Ingresos Financieros de Instituciones Financieras','tipo'=>'R'],
['codigo'=>'11900','nombre'=>'Otros Ingresos de Operación','tipo'=>'R'],
['codigo'=>'12000','nombre'=>'VENTA DE BIENES Y SERVICIOS DE LAS ADMINISTRACIONES PÚBLICAS','tipo'=>'R'],
['codigo'=>'12100','nombre'=>'Venta de Bienes de las Administraciones Públicas','tipo'=>'R'],
['codigo'=>'12200','nombre'=>'Venta de Servicios de las Administraciones Públicas','tipo'=>'R'],
['codigo'=>'13000','nombre'=>'INGRESOS POR IMPUESTOS','tipo'=>'R'],
['codigo'=>'13100','nombre'=>'Impuestos Internos (Renta Interna)','tipo'=>'R'],
['codigo'=>'13110','nombre'=>'Impuesto sobre las Utilidades de las Empresas','tipo'=>'R'],
['codigo'=>'13111','nombre'=>'En Efectivo','tipo'=>'R'],
['codigo'=>'13112','nombre'=>'En Certificados de Crédito Fiscal','tipo'=>'R'],
['codigo'=>'13120','nombre'=>'Impuesto a las Transacciones','tipo'=>'R'],
['codigo'=>'13121','nombre'=>'En Efectivo','tipo'=>'R'],
['codigo'=>'13122','nombre'=>'En Certificados de Crédito Fiscal','tipo'=>'R'],
['codigo'=>'13130','nombre'=>'Impuesto al Valor Agregado - Mercado Interno','tipo'=>'R'],
['codigo'=>'13131','nombre'=>'En Efectivo','tipo'=>'R'],
['codigo'=>'13132','nombre'=>'En Certificados de Crédito Fiscal','tipo'=>'R'],
['codigo'=>'13140','nombre'=>'Impuesto al Valor Agregado - Importaciones','tipo'=>'R'],
['codigo'=>'13141','nombre'=>'En Efectivo','tipo'=>'R'],
['codigo'=>'13142','nombre'=>'En Certificados de Crédito Fiscal','tipo'=>'R'],
['codigo'=>'13150','nombre'=>'Impuesto a los Consumos Específicos - Mercado Interno','tipo'=>'R'],
['codigo'=>'13151','nombre'=>'En Efectivo','tipo'=>'R'],
['codigo'=>'13152','nombre'=>'En Certificados de Crédito Fiscal','tipo'=>'R'],
['codigo'=>'13160','nombre'=>'Impuesto a los Consumos Específicos - Importaciones','tipo'=>'R'],
['codigo'=>'13161','nombre'=>'En Efectivo','tipo'=>'R'],
['codigo'=>'13162','nombre'=>'En Certificados de Crédito Fiscal','tipo'=>'R'],
['codigo'=>'13170','nombre'=>'Impuestos a los Hidrocarburos','tipo'=>'R'],
['codigo'=>'13171','nombre'=>'Impuesto Especial a los Hidrocarburos y sus Derivados Mercado Interno - En Efectivo','tipo'=>'R'],
['codigo'=>'13172','nombre'=>'Impuesto Especial a los Hidrocarburos y sus Derivados Mercado Interno - En Certificados de Crédito Fiscal','tipo'=>'R'],
['codigo'=>'13175','nombre'=>'Impuesto Directo a los Hidrocarburos','tipo'=>'R'],
['codigo'=>'13190','nombre'=>'Otros Impuestos','tipo'=>'R'],
['codigo'=>'13191','nombre'=>'Régimen Complementario al IVA - RC IVA','tipo'=>'R'],
['codigo'=>'13192','nombre'=>'Impuesto a las Salidas Aéreas al Exterior - ISAE','tipo'=>'R'],
['codigo'=>'13193','nombre'=>'Impuesto a la Transmisión Gratuita de Bienes - ITGB','tipo'=>'R'],
['codigo'=>'13194','nombre'=>'Régimen Agropecuario Unificado - RAU','tipo'=>'R'],
['codigo'=>'13195','nombre'=>'Régimen Tributario Simplificado - RTS','tipo'=>'R'],
['codigo'=>'13196','nombre'=>'Régimen Tributario Integrado - STI','tipo'=>'R'],
['codigo'=>'13197','nombre'=>'En Certificados de Crédito Fiscal','tipo'=>'R'],
['codigo'=>'13198','nombre'=>'Impuesto a las Transacciones Financieras - ITF','tipo'=>'R'],
['codigo'=>'13199','nombre'=>'Impuestos a la Participación en Juegos, a la Venta de Moneda Extranjera y Otros','tipo'=>'R'],
['codigo'=>'13200','nombre'=>'Impuestos Aduaneros (Renta Aduanera)','tipo'=>'R'],
['codigo'=>'13210','nombre'=>'Gravamen Arancelario','tipo'=>'R'],
['codigo'=>'13211','nombre'=>'En Efectivo','tipo'=>'R'],
['codigo'=>'13212','nombre'=>'En Certificados de Crédito Fiscal','tipo'=>'R'],
['codigo'=>'13300','nombre'=>'Impuestos Municipales','tipo'=>'R'],
['codigo'=>'13310','nombre'=>'Impuesto a la Propiedad de Bienes Inmuebles','tipo'=>'R'],
['codigo'=>'13330','nombre'=>'Impuesto a la Propiedad de Vehículos Automotores','tipo'=>'R'],
['codigo'=>'13360','nombre'=>'Impuesto Municipal a la Transferencia de Inmuebles','tipo'=>'R'],
['codigo'=>'13370','nombre'=>'Impuesto Municipal a la Transferencia de Vehículos Automotores','tipo'=>'R'],
['codigo'=>'13390','nombre'=>'Otros','tipo'=>'R'],
['codigo'=>'13400','nombre'=>'Impuestos Departamentales','tipo'=>'R'],
['codigo'=>'13410','nombre'=>'Impuesto a la Sucesión Hereditaria y Donación de Bienes Inmuebles y Muebles Sujetos a Registro Público','tipo'=>'R'],
['codigo'=>'13420','nombre'=>'Impuesto a la Propiedad de Vehículos a motor para la navegación Aérea y Acuática','tipo'=>'R'],
['codigo'=>'13430','nombre'=>'Impuesto a la afectación del Medio Ambiente','tipo'=>'R'],
['codigo'=>'13490','nombre'=>'Otros','tipo'=>'R'],
['codigo'=>'14000','nombre'=>'REGALIAS','tipo'=>'R'],
['codigo'=>'14100','nombre'=>'Regalías Mineras','tipo'=>'R'],
['codigo'=>'14200','nombre'=>'Regalías por Hidrocarburos','tipo'=>'R'],
['codigo'=>'14210','nombre'=>'Nacionales','tipo'=>'R'],
['codigo'=>'14212','nombre'=>'6% Participación TGN','tipo'=>'R'],
['codigo'=>'14220','nombre'=>'Departamentales','tipo'=>'R'],
['codigo'=>'14221','nombre'=>'11% Regalías Departamentales','tipo'=>'R'],
['codigo'=>'14222','nombre'=>'1% Regalía Compensatoria Departamental','tipo'=>'R'],
['codigo'=>'14300','nombre'=>'Regalías Agropecuarias y Forestales','tipo'=>'R'],
['codigo'=>'14900','nombre'=>'Otras Regalías','tipo'=>'R'],
['codigo'=>'15000','nombre'=>'TASAS, DERECHOS Y OTROS INGRESOS','tipo'=>'R'],
['codigo'=>'15100','nombre'=>'Tasas','tipo'=>'R'],
['codigo'=>'15200','nombre'=>'Derechos','tipo'=>'R'],
['codigo'=>'15300','nombre'=>'Patentes y Concesiones','tipo'=>'R'],
['codigo'=>'15310','nombre'=>'Patentes Forestales','tipo'=>'R'],
['codigo'=>'15320','nombre'=>'Patentes Petroleras','tipo'=>'R'],
['codigo'=>'15330','nombre'=>'Patentes y Concesiones Mineras','tipo'=>'R'],
['codigo'=>'15331','nombre'=>'Patentes Mineras','tipo'=>'R'],
['codigo'=>'15332','nombre'=>'Concesiones Mineras','tipo'=>'R'],
['codigo'=>'15340','nombre'=>'Patentes Municipales','tipo'=>'R'],
['codigo'=>'15350','nombre'=>'Otras Patentes y Concesiones','tipo'=>'R'],
['codigo'=>'Otras','nombre'=>'patentes y concesiones no especificadas en los rubros precedentes.','tipo'=>'R'],
['codigo'=>'15400','nombre'=>'Contribuciones por Mejoras','tipo'=>'R'],
['codigo'=>'15900','nombre'=>'Otros Ingresos','tipo'=>'R'],
['codigo'=>'15910','nombre'=>'Multas','tipo'=>'R'],
['codigo'=>'15920','nombre'=>'Intereses Penales','tipo'=>'R'],
['codigo'=>'15930','nombre'=>'Ganancias en Operaciones Cambiarias','tipo'=>'R'],
['codigo'=>'15940','nombre'=>'Renta Consular','tipo'=>'R'],
['codigo'=>'15990','nombre'=>'Otros Ingresos no Especificados','tipo'=>'R'],
['codigo'=>'16000','nombre'=>'INTERESES Y OTRAS RENTAS DE LA PROPIEDAD','tipo'=>'R'],
['codigo'=>'16100','nombre'=>'Intereses','tipo'=>'R'],
['codigo'=>'16110','nombre'=>'Intereses por Depósitos','tipo'=>'R'],
['codigo'=>'16120','nombre'=>'Intereses por Valores','tipo'=>'R'],
['codigo'=>'16140','nombre'=>'Intereses por Inversiones en instrumentos financieros en el extranjero','tipo'=>'R'],
['codigo'=>'16190','nombre'=>'Otros Intereses','tipo'=>'R'],
['codigo'=>'16200','nombre'=>'Dividendos','tipo'=>'R'],
['codigo'=>'16300','nombre'=>'Alquiler de Edificios, Tierras y Terrenos','tipo'=>'R'],
['codigo'=>'16400','nombre'=>'Derechos sobre Bienes Intangibles','tipo'=>'R'],
['codigo'=>'16500','nombre'=>'Alquiler de Equipos de las Administraciones Públicas','tipo'=>'R'],
['codigo'=>'17000','nombre'=>'CONTRIBUCIONES A LA SEGURIDAD SOCIAL','tipo'=>'R'],
['codigo'=>'17100','nombre'=>'Contribuciones Obligatorias','tipo'=>'R'],
['codigo'=>'17110','nombre'=>'Patronales','tipo'=>'R'],
['codigo'=>'17111','nombre'=>'Del Sector Público','tipo'=>'R'],
['codigo'=>'17112','nombre'=>'Del Sector Privado','tipo'=>'R'],
['codigo'=>'17120','nombre'=>'Laborales','tipo'=>'R'],
['codigo'=>'17121','nombre'=>'Del Sector Público','tipo'=>'R'],
['codigo'=>'17122','nombre'=>'Del Sector Privado','tipo'=>'R'],
['codigo'=>'17130','nombre'=>'Especiales de las Universidades Públicas','tipo'=>'R'],
['codigo'=>'17200','nombre'=>'Contribuciones Voluntarias','tipo'=>'R'],
['codigo'=>'18000','nombre'=>'DONACIONES CORRIENTES','tipo'=>'R'],
['codigo'=>'18100','nombre'=>'Donaciones Corrientes Internas','tipo'=>'R'],
['codigo'=>'18110','nombre'=>'Del Sector Privado Nacional realizados por personas naturales y jurídicas.','tipo'=>'R'],
['codigo'=>'18111','nombre'=>'Monetizables','tipo'=>'R'],
['codigo'=>'18112','nombre'=>'No Monetizable','tipo'=>'R'],
['codigo'=>'18200','nombre'=>'Donaciones Corrientes del Exterior','tipo'=>'R'],
['codigo'=>'18210','nombre'=>'Del Sector Privado del Exterior','tipo'=>'R'],
['codigo'=>'18211','nombre'=>'Monetizable','tipo'=>'R'],
['codigo'=>'18212','nombre'=>'No Monetizable','tipo'=>'R'],
['codigo'=>'18220','nombre'=>'De Países y Organismos Internacionales','tipo'=>'R'],
['codigo'=>'18221','nombre'=>'Monetizable','tipo'=>'R'],
['codigo'=>'18222','nombre'=>'No Monetizable','tipo'=>'R'],
['codigo'=>'19000','nombre'=>'TRANSFERENCIAS CORRIENTES','tipo'=>'R'],
['codigo'=>'19100','nombre'=>'Del Sector Privado','tipo'=>'R'],
['codigo'=>'19110','nombre'=>'De Unidades Familiares','tipo'=>'R'],
['codigo'=>'19120','nombre'=>'De Instituciones Privadas sin Fines de Lucro','tipo'=>'R'],
['codigo'=>'19130','nombre'=>'De Empresas Privadas','tipo'=>'R'],
['codigo'=>'19200','nombre'=>'Del Sector Público No Financiero','tipo'=>'R'],
['codigo'=>'19210','nombre'=>'Del Órgano Ejecutivo','tipo'=>'R'],
['codigo'=>'19211','nombre'=>'Por Subsidios o Subvenciones','tipo'=>'R'],
['codigo'=>'19212','nombre'=>'Por Coparticipación Tributaria','tipo'=>'R'],
['codigo'=>'19216','nombre'=>'Fondo de Compensación Departamental','tipo'=>'R'],
['codigo'=>'19219','nombre'=>'Por Emisión de Certificados de Crédito Fiscal','tipo'=>'R'],
['codigo'=>'19220','nombre'=>'De los Órganos Legislativo, Judicial y Electoral, Entidades de Control y Defensa, Descentralizadas y Universidades','tipo'=>'R'],
['codigo'=>'19230','nombre'=>'De las Entidades Territoriales Autónomas','tipo'=>'R'],
['codigo'=>'19231','nombre'=>'Del Gobierno Autónomo Departamental','tipo'=>'R'],
['codigo'=>'19232','nombre'=>'Del Gobierno Autónomo Municipal','tipo'=>'R'],
['codigo'=>'19233','nombre'=>'Del Gobierno Autónomo Indígena Originario Campesino','tipo'=>'R'],
['codigo'=>'19234','nombre'=>'Del Gobierno Autónomo Regional','tipo'=>'R'],
['codigo'=>'19260','nombre'=>'De las Instituciones de Seguridad Social','tipo'=>'R'],
['codigo'=>'19270','nombre'=>'De las Empresas Públicas Nacionales','tipo'=>'R'],
['codigo'=>'19271','nombre'=>'Por Subsidios y Subvenciones','tipo'=>'R'],
['codigo'=>'19272','nombre'=>'Por Excedentes Financieros','tipo'=>'R'],
['codigo'=>'19280','nombre'=>'De las Empresas Públicas Territoriales','tipo'=>'R'],
['codigo'=>'19281','nombre'=>'Del Gobierno Autónomo Departamental','tipo'=>'R'],
['codigo'=>'19282','nombre'=>'Del Gobierno Autónomo Municipal','tipo'=>'R'],
['codigo'=>'19283','nombre'=>'Del Gobierno Autónomo Indígena Originario Campesino','tipo'=>'R'],
['codigo'=>'19284','nombre'=>'Del Gobierno Autónomo Regional','tipo'=>'R'],
['codigo'=>'19300','nombre'=>'Del Sector Público Financiero','tipo'=>'R'],
['codigo'=>'19310','nombre'=>'De las Instituciones Públicas Financieras No Bancarias','tipo'=>'R'],
['codigo'=>'19320','nombre'=>'De las Instituciones Públicas Financieras Bancarias','tipo'=>'R'],
['codigo'=>'19400','nombre'=>'Del Exterior','tipo'=>'R'],
['codigo'=>'21000','nombre'=>'RECURSOS PROPIOS DE CAPITAL','tipo'=>'R'],
['codigo'=>'21100','nombre'=>'Venta de Activos Fijos','tipo'=>'R'],
['codigo'=>'21110','nombre'=>'Edificios','tipo'=>'R'],
['codigo'=>'21120','nombre'=>'Maquinaria y Equipo','tipo'=>'R'],
['codigo'=>'21121','nombre'=>'Equipo de Oficina y Muebles','tipo'=>'R'],
['codigo'=>'21122','nombre'=>'Maquinaria y Equipo de Producción','tipo'=>'R'],
['codigo'=>'21123','nombre'=>'Equipo de Transporte, Tracción y Elevación','tipo'=>'R'],
['codigo'=>'21124','nombre'=>'Equipo Médico y de Laboratorio','tipo'=>'R'],
['codigo'=>'21125','nombre'=>'Equipo de Comunicación','tipo'=>'R'],
['codigo'=>'21126','nombre'=>'Equipo Educacional y Recreativo','tipo'=>'R'],
['codigo'=>'21127','nombre'=>'Otra Maquinaria y Equipo','tipo'=>'R'],
['codigo'=>'21130','nombre'=>'Semovientes','tipo'=>'R'],
['codigo'=>'21200','nombre'=>'Venta de Tierras y Terrenos','tipo'=>'R'],
['codigo'=>'21400','nombre'=>'Venta de Activos Intangibles','tipo'=>'R'],
['codigo'=>'21900','nombre'=>'Venta de Otros Activos Fijos','tipo'=>'R'],
['codigo'=>'22000','nombre'=>'DONACIONES DE CAPITAL','tipo'=>'R'],
['codigo'=>'22100','nombre'=>'Donaciones de Capital Internas','tipo'=>'R'],
['codigo'=>'22110','nombre'=>'Del Sector Privado Nacional realizados por personas naturales y jurídicas.','tipo'=>'R'],
['codigo'=>'22111','nombre'=>'Monetizables','tipo'=>'R'],
['codigo'=>'22112','nombre'=>'No Monetizable','tipo'=>'R'],
['codigo'=>'22200','nombre'=>'Donaciones de Capital del Exterior','tipo'=>'R'],
['codigo'=>'22210','nombre'=>'Del Sector Privado del Exterior','tipo'=>'R'],
['codigo'=>'22211','nombre'=>'Monetizable','tipo'=>'R'],
['codigo'=>'22212','nombre'=>'No Monetizable','tipo'=>'R'],
['codigo'=>'22220','nombre'=>'De Países y Organismos Internacionales','tipo'=>'R'],
['codigo'=>'22221','nombre'=>'Monetizable','tipo'=>'R'],
['codigo'=>'22222','nombre'=>'No Monetizable','tipo'=>'R'],
['codigo'=>'22223','nombre'=>'Donaciones HIPC','tipo'=>'R'],
['codigo'=>'23000','nombre'=>'TRANSFERENCIAS DE CAPITAL','tipo'=>'R'],
['codigo'=>'23100','nombre'=>'Del Sector Privado','tipo'=>'R'],
['codigo'=>'23110','nombre'=>'De Unidades Familiares','tipo'=>'R'],
['codigo'=>'23120','nombre'=>'De Instituciones Privadas sin Fines de Lucro','tipo'=>'R'],
['codigo'=>'23130','nombre'=>'De Empresas Privadas','tipo'=>'R'],
['codigo'=>'23200','nombre'=>'Del Sector Público No Financiero','tipo'=>'R'],
['codigo'=>'23210','nombre'=>'Del Órgano Ejecutivo','tipo'=>'R'],
['codigo'=>'23211','nombre'=>'Por Subsidios o Subvenciones','tipo'=>'R'],
['codigo'=>'23212','nombre'=>'Por Patentes Petroleras','tipo'=>'R'],
['codigo'=>'23219','nombre'=>'En Certificados de Crédito Fiscal','tipo'=>'R'],
['codigo'=>'23220','nombre'=>'De los Órganos Legislativo, Judicial y Electoral, Entidades de Control y Defensa, Descentralizadas y Universidades','tipo'=>'R'],
['codigo'=>'23230','nombre'=>'De las Entidades Territoriales Autónomas','tipo'=>'R'],
['codigo'=>'23231','nombre'=>'Del Gobierno Autónomo Departamental','tipo'=>'R'],
['codigo'=>'23232','nombre'=>'Del Gobierno Autónomo Municipal','tipo'=>'R'],
['codigo'=>'23233','nombre'=>'Del Gobierno Autónomo Indígena Originario Campesino','tipo'=>'R'],
['codigo'=>'23234','nombre'=>'Del Gobierno Autónomo Regional','tipo'=>'R'],
['codigo'=>'23260','nombre'=>'De las Instituciones de Seguridad Social','tipo'=>'R'],
['codigo'=>'23270','nombre'=>'De las Empresas Públicas Nacionales','tipo'=>'R'],
['codigo'=>'23271','nombre'=>'Por Subsidios y Subvenciones','tipo'=>'R'],
['codigo'=>'23272','nombre'=>'Por Excedentes Financieros','tipo'=>'R'],
['codigo'=>'23280','nombre'=>'De las Empresas Públicas Territoriales','tipo'=>'R'],
['codigo'=>'23281','nombre'=>'Del Gobierno Autónomo Departamental','tipo'=>'R'],
['codigo'=>'23282','nombre'=>'Del Gobierno Autónomo Municipal','tipo'=>'R'],
['codigo'=>'23283','nombre'=>'Del Gobierno Autónomo Indígena Originario Campesino','tipo'=>'R'],
['codigo'=>'23284','nombre'=>'Del Gobierno Autónomo Regional','tipo'=>'R'],
['codigo'=>'23300','nombre'=>'Del Sector Público Financiero','tipo'=>'R'],
['codigo'=>'23310','nombre'=>'De las Instituciones Públicas Financieras No Bancarias','tipo'=>'R'],
['codigo'=>'23320','nombre'=>'De las Instituciones Públicas Financieras Bancarias','tipo'=>'R'],
['codigo'=>'23400','nombre'=>'Del Exterior','tipo'=>'R'],
['codigo'=>'31000','nombre'=>'VENTA DE ACCIONES Y PARTICIPACIONES DE CAPITAL','tipo'=>'R'],
['codigo'=>'31100','nombre'=>'De Empresas Privadas Nacionales','tipo'=>'R'],
['codigo'=>'31200','nombre'=>'De Empresas Públicas','tipo'=>'R'],
['codigo'=>'31210','nombre'=>'De las Empresas Públicas Nacionales','tipo'=>'R'],
['codigo'=>'31220','nombre'=>'De las Empresas Públicas Departamentales','tipo'=>'R'],
['codigo'=>'31230','nombre'=>'De las Empresas Públicas Municipales','tipo'=>'R'],
['codigo'=>'31240','nombre'=>'De las Empresas Públicas Regionales','tipo'=>'R'],
['codigo'=>'31250','nombre'=>'De las Empresas Públicas Indígena Originaria Campesina','tipo'=>'R'],
['codigo'=>'31300','nombre'=>'De Instituciones Públicas Financieras','tipo'=>'R'],
['codigo'=>'31310','nombre'=>'De las Instituciones Públicas Financieras No Bancarias','tipo'=>'R'],
['codigo'=>'31320','nombre'=>'De las Instituciones Públicas Financieras Bancarias','tipo'=>'R'],
['codigo'=>'31400','nombre'=>'Del Exterior','tipo'=>'R'],
['codigo'=>'31410','nombre'=>'De Organismos Internacionales','tipo'=>'R'],
['codigo'=>'31420','nombre'=>'Otras del Exterior','tipo'=>'R'],
['codigo'=>'32000','nombre'=>'RECUPERACION DE PRÉSTAMOS DE CORTO PLAZO','tipo'=>'R'],
['codigo'=>'32100','nombre'=>'Del Sector Privado','tipo'=>'R'],
['codigo'=>'32200','nombre'=>'Del Sector Público No Financiero','tipo'=>'R'],
['codigo'=>'32210','nombre'=>'Del Órgano Ejecutivo','tipo'=>'R'],
['codigo'=>'32211','nombre'=>'En Efectivo','tipo'=>'R'],
['codigo'=>'32212','nombre'=>'En Certificados de Crédito Fiscal','tipo'=>'R'],
['codigo'=>'32220','nombre'=>'De los Órganos Legislativo, Judicial y Electoral, Entidades de Control y Defensa, Descentralizadas y Universidades','tipo'=>'R'],
['codigo'=>'32230','nombre'=>'De las Entidades Territoriales Autónomas','tipo'=>'R'],
['codigo'=>'32231','nombre'=>'Del Gobierno Autónomo Departamental','tipo'=>'R'],
['codigo'=>'32232','nombre'=>'Del Gobierno Autónomo Municipal','tipo'=>'R'],
['codigo'=>'32233','nombre'=>'Del Gobierno Autónomo Indígena Originario Campesino','tipo'=>'R'],
['codigo'=>'32234','nombre'=>'Del Gobierno Autónomo Regional','tipo'=>'R'],
['codigo'=>'32260','nombre'=>'De las Instituciones de Seguridad Social','tipo'=>'R'],
['codigo'=>'32270','nombre'=>'De las Empresas Públicas Nacionales','tipo'=>'R'],
['codigo'=>'32280','nombre'=>'De las Empresas Públicas Territoriales','tipo'=>'R'],
['codigo'=>'32281','nombre'=>'Del Gobierno Autónomo Departamental','tipo'=>'R'],
['codigo'=>'32282','nombre'=>'Del Gobierno Autónomo Municipal','tipo'=>'R'],
['codigo'=>'32283','nombre'=>'Del Gobierno Autónomo Indígena Originario Campesino','tipo'=>'R'],
['codigo'=>'32284','nombre'=>'Del Gobierno Autónomo Regional','tipo'=>'R'],
['codigo'=>'32300','nombre'=>'Del Sector Público Financiero','tipo'=>'R'],
['codigo'=>'32310','nombre'=>'De las Instituciones Públicas Financieras No Bancarias','tipo'=>'R'],
['codigo'=>'32320','nombre'=>'De las Instituciones Públicas Financieras Bancarias','tipo'=>'R'],
['codigo'=>'32400','nombre'=>'Del Exterior','tipo'=>'R'],
['codigo'=>'33000','nombre'=>'RECUPERACION DE PRÉSTAMOS DE LARGO PLAZO','tipo'=>'R'],
['codigo'=>'33100','nombre'=>'Del Sector Privado','tipo'=>'R'],
['codigo'=>'33200','nombre'=>'Del Sector Público No Financiero','tipo'=>'R'],
['codigo'=>'33210','nombre'=>'Del Órgano Ejecutivo','tipo'=>'R'],
['codigo'=>'33211','nombre'=>'En Efectivo','tipo'=>'R'],
['codigo'=>'33212','nombre'=>'En Certificados de Crédito Fiscal','tipo'=>'R'],
['codigo'=>'33220','nombre'=>'De los Órganos Legislativo, Judicial y Electoral, Entidades de Control y Defensa, Descentralizadas y Universidades','tipo'=>'R'],
['codigo'=>'33230','nombre'=>'De las Entidades Territoriales Autónomas','tipo'=>'R'],
['codigo'=>'33231','nombre'=>'Del Gobierno Autónomo Departamental','tipo'=>'R'],
['codigo'=>'33232','nombre'=>'Del Gobierno Autónomo Municipal','tipo'=>'R'],
['codigo'=>'33233','nombre'=>'Del Gobierno Autónomo Indígena Originario Campesino','tipo'=>'R'],
['codigo'=>'33234','nombre'=>'Del Gobierno Autónomo Regional','tipo'=>'R'],
['codigo'=>'33260','nombre'=>'De las Instituciones de Seguridad Social','tipo'=>'R'],
['codigo'=>'33270','nombre'=>'De las Empresas Públicas Nacionales','tipo'=>'R'],
['codigo'=>'33280','nombre'=>'De las Empresas Públicas Territoriales','tipo'=>'R'],
['codigo'=>'33281','nombre'=>'Del Gobierno Autónomo Departamental','tipo'=>'R'],
['codigo'=>'33282','nombre'=>'Del Gobierno Autónomo Municipal','tipo'=>'R'],
['codigo'=>'33283','nombre'=>'Del Gobierno Autónomo Indígena Originario Campesino','tipo'=>'R'],
['codigo'=>'33284','nombre'=>'Del Gobierno Autónomo Regional','tipo'=>'R'],
['codigo'=>'33300','nombre'=>'Del Sector Público Financiero','tipo'=>'R'],
['codigo'=>'33310','nombre'=>'De las Instituciones Públicas Financieras No Bancarias','tipo'=>'R'],
['codigo'=>'33320','nombre'=>'De las Instituciones Públicas Financieras Bancarias','tipo'=>'R'],
['codigo'=>'33400','nombre'=>'Recuperación de Fondos de Fideicomiso y Servicios Financieros','tipo'=>'R'],
['codigo'=>'33410','nombre'=>'De las Instituciones Públicas','tipo'=>'R'],
['codigo'=>'33420','nombre'=>'De las Instituciones Privadas','tipo'=>'R'],
['codigo'=>'33500','nombre'=>'Del Exterior','tipo'=>'R'],
['codigo'=>'33600','nombre'=>'Recuperaciones por Afectaciones al Tesoro General de la Nación','tipo'=>'R'],
['codigo'=>'34000','nombre'=>'VENTA DE TÍTULOS Y VALORES','tipo'=>'R'],
['codigo'=>'34100','nombre'=>'Venta de Títulos y Valores de Corto Plazo','tipo'=>'R'],
['codigo'=>'34110','nombre'=>'Letras del Tesoro','tipo'=>'R'],
['codigo'=>'34120','nombre'=>'Bonos del Tesoro','tipo'=>'R'],
['codigo'=>'34130','nombre'=>'Otros','tipo'=>'R'],
['codigo'=>'34200','nombre'=>'Venta de Títulos y Valores de Largo Plazo','tipo'=>'R'],
['codigo'=>'34210','nombre'=>'Letras del Tesoro','tipo'=>'R'],
['codigo'=>'34220','nombre'=>'Bonos del Tesoro','tipo'=>'R'],
['codigo'=>'34230','nombre'=>'Otros','tipo'=>'R'],
['codigo'=>'35000','nombre'=>'DISMINUCIÓN Y COBRO DE OTROS ACTIVOS FINANCIEROS','tipo'=>'R'],
['codigo'=>'35100','nombre'=>'Disminución del Activo Disponible','tipo'=>'R'],
['codigo'=>'35110','nombre'=>'Disminución de Caja y Bancos','tipo'=>'R'],
['codigo'=>'35120','nombre'=>'Disminución de Inversiones Temporales','tipo'=>'R'],
['codigo'=>'35130','nombre'=>'Disminución de Anticipos Financieros','tipo'=>'R'],
['codigo'=>'35200','nombre'=>'Disminución de Cuentas y Documentos por Cobrar y Otros Activos Financieros a Corto Plazo','tipo'=>'R'],
['codigo'=>'35210','nombre'=>'Disminución de Cuentas por Cobrar a Corto Plazo','tipo'=>'R'],
['codigo'=>'35220','nombre'=>'Disminución de Documentos por Cobrar y Otros Activos Financieros a Corto Plazo','tipo'=>'R'],
['codigo'=>'35221','nombre'=>'Disminución de documentos por cobrar a corto plazo','tipo'=>'R'],
['codigo'=>'35222','nombre'=>'Disminución de otros Activos financieros a corto plazo','tipo'=>'R'],
['codigo'=>'35300','nombre'=>'Disminución de Cuentas y Documentos por Cobrar y Otros Activos Financieros a Largo Plazo','tipo'=>'R'],
['codigo'=>'35310','nombre'=>'Disminución de Cuentas por Cobrar a Largo Plazo','tipo'=>'R'],
['codigo'=>'Fuent','nombre'=>'es financieras que se originan en la disminución neta de saldos de las cuentas por cobrar a largo plazo.','tipo'=>'R'],
['codigo'=>'35320','nombre'=>'Disminución de Documentos por Cobrar y Otros Activos Financieros a Largo Plazo diferidos y débitos por apertura de cartas de crédito a largo plazo.','tipo'=>'R'],
['codigo'=>'35321','nombre'=>'Disminución de documentos por cobrar a largo plazo','tipo'=>'R'],
['codigo'=>'35322','nombre'=>'Disminución de otros Activos financieros a largo plazo','tipo'=>'R'],
['codigo'=>'35400','nombre'=>'Cobro de Cuentas y Documentos por Cobrar y Otros Activos Financieros a Corto Plazo','tipo'=>'R'],
['codigo'=>'35410','nombre'=>'Recursos Devengados no Cobrados por Cuentas por Cobrar de Corto Plazo','tipo'=>'R'],
['codigo'=>'35420','nombre'=>'Recursos Devengados no Cobrados por Documentos por Cobrar y Otros Activos Financieros a Corto Plazo','tipo'=>'R'],
['codigo'=>'36000','nombre'=>'OBTENCIÓN DE PRÉSTAMOS INTERNOS Y DE FONDOS - FIDEICOMISOS','tipo'=>'R'],
['codigo'=>'36100','nombre'=>'Obtención de Préstamos Internos a Corto Plazo','tipo'=>'R'],
['codigo'=>'36110','nombre'=>'En Efectivo','tipo'=>'R'],
['codigo'=>'36120','nombre'=>'En Certificados de Crédito Fiscal','tipo'=>'R'],
['codigo'=>'36200','nombre'=>'Obtención de Préstamos Internos a Largo Plazo','tipo'=>'R'],
['codigo'=>'36210','nombre'=>'En Efectivo','tipo'=>'R'],
['codigo'=>'36220','nombre'=>'En Certificados de Crédito Fiscal','tipo'=>'R'],
['codigo'=>'36300','nombre'=>'Obtención de Fondos en Fideicomiso','tipo'=>'R'],
['codigo'=>'36310','nombre'=>'Obtención de Fondos - Fideicomiso a Corto Plazo','tipo'=>'R'],
['codigo'=>'36320','nombre'=>'Obtención de Fondos - Fideicomiso a Largo Plazo','tipo'=>'R'],
['codigo'=>'36400','nombre'=>'Financiamiento por Afectaciones al Tesoro General de la Nación','tipo'=>'R'],
['codigo'=>'37000','nombre'=>'OBTENCIÓN DE PRÉSTAMOS DEL EXTERIOR','tipo'=>'R'],
['codigo'=>'37100','nombre'=>'Obtención de Préstamos del Exterior a Corto Plazo','tipo'=>'R'],
['codigo'=>'37110','nombre'=>'Del Sector Privado del Exterior','tipo'=>'R'],
['codigo'=>'37111','nombre'=>'Monetizable','tipo'=>'R'],
['codigo'=>'37112','nombre'=>'No Monetizable','tipo'=>'R'],
['codigo'=>'37120','nombre'=>'De Países y Organismos Internacionales','tipo'=>'R'],
['codigo'=>'37121','nombre'=>'Monetizable','tipo'=>'R'],
['codigo'=>'37122','nombre'=>'No Monetizable','tipo'=>'R'],
['codigo'=>'37200','nombre'=>'Obtención de Préstamos del Exterior a Largo Plazo','tipo'=>'R'],
['codigo'=>'37210','nombre'=>'Del Sector Privado del Exterior','tipo'=>'R'],
['codigo'=>'37211','nombre'=>'Monetizable','tipo'=>'R'],
['codigo'=>'37212','nombre'=>'No Monetizable','tipo'=>'R'],
['codigo'=>'37220','nombre'=>'De Países y Organismos Internacionales','tipo'=>'R'],
['codigo'=>'37221','nombre'=>'Monetizable','tipo'=>'R'],
['codigo'=>'37222','nombre'=>'No Monetizable','tipo'=>'R'],
['codigo'=>'38000','nombre'=>'EMISIÓN DE TÍTULOS DE DEUDA','tipo'=>'R'],
['codigo'=>'38100','nombre'=>'Títulos y Valores Internos de Corto Plazo','tipo'=>'R'],
['codigo'=>'38200','nombre'=>'Títulos y Valores Internos de Largo Plazo','tipo'=>'R'],
['codigo'=>'38300','nombre'=>'Títulos y Valores Externos de Corto Plazo','tipo'=>'R'],
['codigo'=>'38400','nombre'=>'Títulos y Valores Externos de Largo Plazo','tipo'=>'R'],
['codigo'=>'39000','nombre'=>'INCREMENTO DE OTROS PASIVOS Y APORTES DE CAPITAL','tipo'=>'R'],
['codigo'=>'39100','nombre'=>'Incremento de Cuentas por Pagar a Corto Plazo','tipo'=>'R'],
['codigo'=>'39110','nombre'=>'Incremento de Cuentas por Pagar a Corto Plazo por Deudas Comerciales','tipo'=>'R'],
['codigo'=>'39120','nombre'=>'Incremento de Cuentas por Pagar a Corto Plazo con Contratistas','tipo'=>'R'],
['codigo'=>'39130','nombre'=>'Incremento de Cuentas por Pagar a Corto Plazo por Sueldos y Jornales','tipo'=>'R'],
['codigo'=>'39140','nombre'=>'Incremento de Cuentas por Pagar a Corto Plazo por Aportes Patronales','tipo'=>'R'],
['codigo'=>'39150','nombre'=>'Incremento de Cuentas por Pagar a Corto Plazo por Retenciones','tipo'=>'R'],
['codigo'=>'39160','nombre'=>'Incremento de Cuentas por Pagar a Corto Plazo por Impuestos, Regalías y Tasas','tipo'=>'R'],
['codigo'=>'39170','nombre'=>'Incremento de Cuentas por Pagar a Corto Plazo por Jubilaciones y Pensiones','tipo'=>'R'],
['codigo'=>'39180','nombre'=>'Incremento de Cuentas por Pagar a Corto Plazo por Intereses','tipo'=>'R'],
['codigo'=>'39190','nombre'=>'Incremento de Otros Pasivos y Otras Cuentas por Pagar a Corto Plazo','tipo'=>'R'],
['codigo'=>'39200','nombre'=>'Incremento de Cuentas por Pagar a Largo Plazo','tipo'=>'R'],
['codigo'=>'39210','nombre'=>'Incremento de Cuentas por Pagar a Largo Plazo por Deudas Comerciales','tipo'=>'R'],
['codigo'=>'39220','nombre'=>'Incremento de Otras Cuentas por Pagar a Largo Plazo','tipo'=>'R'],
['codigo'=>'39300','nombre'=>'Aportes de Capital','tipo'=>'R'],
['codigo'=>'39310','nombre'=>'Del Sector Público','tipo'=>'R'],
['codigo'=>'39320','nombre'=>'Del Sector Privado','tipo'=>'R'],
['codigo'=>'10000','nombre'=>'SERVICIOS PERSONALES','tipo'=>'G'],
['codigo'=>'11000','nombre'=>'Empleados Permanentes','tipo'=>'G'],
['codigo'=>'11100','nombre'=>'Haberes Básicos','tipo'=>'G'],
['codigo'=>'11200','nombre'=>'Bono de Antigüedad.','tipo'=>'G'],
['codigo'=>'11210','nombre'=>'Categorías Magisterio','tipo'=>'G'],
['codigo'=>'11220','nombre'=>'Bono de Antigüedad','tipo'=>'G'],
['codigo'=>'11300','nombre'=>'Bonificaciones','tipo'=>'G'],
['codigo'=>'11310','nombre'=>'Bono de Frontera','tipo'=>'G'],
['codigo'=>'11320','nombre'=>'Remuneraciones Colaterales Médicas y de Trabajadores en Salud','tipo'=>'G'],
['codigo'=>'11321','nombre'=>'Categorías Médicas','tipo'=>'G'],
['codigo'=>'11322','nombre'=>'Escalafón Médico','tipo'=>'G'],
['codigo'=>'11323','nombre'=>'Escalafón de los Trabajadores en Salud','tipo'=>'G'],
['codigo'=>'11324','nombre'=>'Otras Remuneraciones','tipo'=>'G'],
['codigo'=>'11330','nombre'=>'Otras Bonificaciones','tipo'=>'G'],
['codigo'=>'11400','nombre'=>'Aguinaldos','tipo'=>'G'],
['codigo'=>'11500','nombre'=>'Primas y Bono de Producción','tipo'=>'G'],
['codigo'=>'11510','nombre'=>'Primas','tipo'=>'G'],
['codigo'=>'11520','nombre'=>'Bono de Producción','tipo'=>'G'],
['codigo'=>'11600','nombre'=>'Asignaciones Familiares','tipo'=>'G'],
['codigo'=>'11700','nombre'=>'Sueldos','tipo'=>'G'],
['codigo'=>'11800','nombre'=>'Dietas','tipo'=>'G'],
['codigo'=>'11810','nombre'=>'Dietas de Directorio','tipo'=>'G'],
['codigo'=>'11820','nombre'=>'Otras Dietas','tipo'=>'G'],
['codigo'=>'11900','nombre'=>'Otros Servicios Personales','tipo'=>'G'],
['codigo'=>'11910','nombre'=>'Horas Extraordinarias','tipo'=>'G'],
['codigo'=>'11920','nombre'=>'Vacaciones no Utilizadas','tipo'=>'G'],
['codigo'=>'11930','nombre'=>'Incentivos Económicos','tipo'=>'G'],
['codigo'=>'11940','nombre'=>'Suplencias','tipo'=>'G'],
['codigo'=>'12000','nombre'=>'Empleados No Permanentes','tipo'=>'G'],
['codigo'=>'12100','nombre'=>'Personal Eventual','tipo'=>'G'],
['codigo'=>'13000','nombre'=>'Previsión Social','tipo'=>'G'],
['codigo'=>'13100','nombre'=>'Aporte Patronal al Seguro Social','tipo'=>'G'],
['codigo'=>'13110','nombre'=>'Régimen de Corto Plazo (Salud)','tipo'=>'G'],
['codigo'=>'13120','nombre'=>'Prima de Riesgo Profesional Régimen de Largo Plazo','tipo'=>'G'],
['codigo'=>'13130','nombre'=>'Aporte Patronal Fondo Solidario Régimen de Largo Plazo','tipo'=>'G'],
['codigo'=>'13131','nombre'=>'Aporte Patronal Solidario 3%','tipo'=>'G'],
['codigo'=>'13132','nombre'=>'Aporte Patronal Minero Solidario 2%','tipo'=>'G'],
['codigo'=>'13200','nombre'=>'Aporte Patronal para Vivienda','tipo'=>'G'],
['codigo'=>'14000','nombre'=>'Otros','tipo'=>'G'],
['codigo'=>'14100','nombre'=>'Otros','tipo'=>'G'],
['codigo'=>'15000','nombre'=>'Previsiones para Incremento de Gastos en Servicios Personales','tipo'=>'G'],
['codigo'=>'15100','nombre'=>'Incremento Salarial','tipo'=>'G'],
['codigo'=>'15200','nombre'=>'Crecimiento Vegetativo','tipo'=>'G'],
['codigo'=>'15300','nombre'=>'Creación de Ítems','tipo'=>'G'],
['codigo'=>'15400','nombre'=>'Otras Previsiones','tipo'=>'G'],
['codigo'=>'20000','nombre'=>'SERVICIOS NO PERSONALES','tipo'=>'G'],
['codigo'=>'21000','nombre'=>'Servicios Básicos','tipo'=>'G'],
['codigo'=>'21100','nombre'=>'Comunicaciones','tipo'=>'G'],
['codigo'=>'21200','nombre'=>'Energía Eléctrica','tipo'=>'G'],
['codigo'=>'21300','nombre'=>'Agua','tipo'=>'G'],
['codigo'=>'21400','nombre'=>'Telefonía','tipo'=>'G'],
['codigo'=>'21500','nombre'=>'Gas Domiciliario','tipo'=>'G'],
['codigo'=>'21600','nombre'=>'Internet','tipo'=>'G'],
['codigo'=>'22000','nombre'=>'Servicios de Transporte y Seguros','tipo'=>'G'],
['codigo'=>'22100','nombre'=>'Pasajes','tipo'=>'G'],
['codigo'=>'22110','nombre'=>'Pasajes al Interior del País','tipo'=>'G'],
['codigo'=>'22120','nombre'=>'Pasajes al Exterior del País','tipo'=>'G'],
['codigo'=>'22200','nombre'=>'Viáticos','tipo'=>'G'],
['codigo'=>'22210','nombre'=>'Viáticos por Viajes al Interior del País.','tipo'=>'G'],
['codigo'=>'22220','nombre'=>'Viáticos por Viajes al Exterior del País.','tipo'=>'G'],
['codigo'=>'22300','nombre'=>'Fletes y Almacenamiento','tipo'=>'G'],
['codigo'=>'22400','nombre'=>'Gastos de Instalación y Retorno','tipo'=>'G'],
['codigo'=>'22500','nombre'=>'Seguros','tipo'=>'G'],
['codigo'=>'22600','nombre'=>'Transporte de Personal','tipo'=>'G'],
['codigo'=>'23000','nombre'=>'Alquileres','tipo'=>'G'],
['codigo'=>'23100','nombre'=>'Alquiler de Inmuebles','tipo'=>'G'],
['codigo'=>'23200','nombre'=>'Alquiler de Equipos y Maquinarias','tipo'=>'G'],
['codigo'=>'23300','nombre'=>'Alquiler de Tierras y Terrenos','tipo'=>'G'],
['codigo'=>'23400','nombre'=>'Otros Alquileres','tipo'=>'G'],
['codigo'=>'24000','nombre'=>'Instalación, Mantenimiento y Reparaciones','tipo'=>'G'],
['codigo'=>'24100','nombre'=>'Mantenimiento y Reparación de Inmuebles y Equipos','tipo'=>'G'],
['codigo'=>'24120','nombre'=>'Mantenimiento y Reparación de Vehículos, Maquinaria y Equipos','tipo'=>'G'],
['codigo'=>'24130','nombre'=>'Mantenimiento y Reparación de Muebles y Enseres','tipo'=>'G'],
['codigo'=>'24200','nombre'=>'Mantenimiento y Reparación de Vías de Comunicación','tipo'=>'G'],
['codigo'=>'24300','nombre'=>'Otros Gastos por Concepto de Instalación, Mantenimiento y Reparación','tipo'=>'G'],
['codigo'=>'25000','nombre'=>'Servicios Profesionales y Comerciales','tipo'=>'G'],
['codigo'=>'25100','nombre'=>'Médicos, Sanitarios y Sociales','tipo'=>'G'],
['codigo'=>'25120','nombre'=>'Gastos Especializados por Atención Médica y otros','tipo'=>'G'],
['codigo'=>'25130','nombre'=>'Gastos por Afiliación de Estudiantes Universitarios al Seguro Social','tipo'=>'G'],
['codigo'=>'25200','nombre'=>'Estudios, Investigaciones, Auditorías Externas y Revalorizaciones','tipo'=>'G'],
['codigo'=>'25210','nombre'=>'Consultorías por Producto','tipo'=>'G'],
['codigo'=>'25220','nombre'=>'Consultores Individuales de Línea','tipo'=>'G'],
['codigo'=>'25230','nombre'=>'Auditorías Externas','tipo'=>'G'],
['codigo'=>'25300','nombre'=>'Comisiones y Gastos Bancarios','tipo'=>'G'],
['codigo'=>'25400','nombre'=>'Lavandería, Limpieza e Higiene','tipo'=>'G'],
['codigo'=>'25500','nombre'=>'Publicidad','tipo'=>'G'],
['codigo'=>'25600','nombre'=>'Servicios de Imprenta, Fotocopiado y Fotográficos','tipo'=>'G'],
['codigo'=>'25700','nombre'=>'Capacitación del Personal','tipo'=>'G'],
['codigo'=>'25800','nombre'=>'Estudios e Investigaciones para Proyectos de Inversión No Capitalizables','tipo'=>'G'],
['codigo'=>'25810','nombre'=>'Consultorías por Producto','tipo'=>'G'],
['codigo'=>'25820','nombre'=>'Consultores Individuales de Línea','tipo'=>'G'],
['codigo'=>'25900','nombre'=>'Servicios Manuales','tipo'=>'G'],
['codigo'=>'26000','nombre'=>'Otros Servicios No Personales','tipo'=>'G'],
['codigo'=>'26200','nombre'=>'Gastos Judiciales','tipo'=>'G'],
['codigo'=>'26300','nombre'=>'Derechos sobre Bienes Intangibles','tipo'=>'G'],
['codigo'=>'26500','nombre'=>'Conjueces y Jueces Ciudadanos','tipo'=>'G'],
['codigo'=>'26600','nombre'=>'Servicio de Seguridad de los Batallones de Seguridad Física de la Policía Nacional y Vigilancia Privada','tipo'=>'G'],
['codigo'=>'26610','nombre'=>'Servicios Públicos','tipo'=>'G'],
['codigo'=>'26620','nombre'=>'Servicios Privados','tipo'=>'G'],
['codigo'=>'26630','nombre'=>'Servicios por Traslado de Valores','tipo'=>'G'],
['codigo'=>'26700','nombre'=>'Servicios de Laboratorios Especializados','tipo'=>'G'],
['codigo'=>'26900','nombre'=>'Otros Servicios No Personales','tipo'=>'G'],
['codigo'=>'26910','nombre'=>'Gastos de Representación','tipo'=>'G'],
['codigo'=>'26920','nombre'=>'Fallas de Caja','tipo'=>'G'],
['codigo'=>'26930','nombre'=>'Pago por Trabajos Dirigidos y Pasantías','tipo'=>'G'],
['codigo'=>'26940','nombre'=>'Compensación Costo de Vida','tipo'=>'G'],
['codigo'=>'26950','nombre'=>'Aguinaldo Esfuerzo por Bolivia""','tipo'=>'G'],
['codigo'=>'26990','nombre'=>'Otros','tipo'=>'G'],
['codigo'=>'27000','nombre'=>'Gastos por Servicios Especializados por la Actividad Extractiva de Recursos Naturales del Estado Plurinacional','tipo'=>'G'],
['codigo'=>'27100','nombre'=>'Servicios por la Extracción, Transformación y Conversión de los Recursos Naturales de Propiedad del Estado Plurinacional.','tipo'=>'G'],
['codigo'=>'27110','nombre'=>'Pago por Costos Incurridos','tipo'=>'G'],
['codigo'=>'27120','nombre'=>'Pago por Utilidades','tipo'=>'G'],
['codigo'=>'30000','nombre'=>'MATERIALES Y SUMINISTROS','tipo'=>'G'],
['codigo'=>'31000','nombre'=>'Alimentos y Productos Agroforestales','tipo'=>'G'],
['codigo'=>'31100','nombre'=>'Alimentos y Bebidas para Personas, Desayuno Escolar y Otros','tipo'=>'G'],
['codigo'=>'31110','nombre'=>'Gastos por Refrigerios al personal permanente, eventual y consultores','tipo'=>'G'],
['codigo'=>'31120','nombre'=>'Gastos por Alimentación y Otros Similares','tipo'=>'G'],
['codigo'=>'31130','nombre'=>'Alimentación Complementaria Escolar','tipo'=>'G'],
['codigo'=>'31140','nombre'=>'Alimentación Hospitalaria, Penitenciaria, Aeronaves y Otras Específicas','tipo'=>'G'],
['codigo'=>'31150','nombre'=>'Alimentos y Bebidas para la atención de emergencias y desastres naturales.','tipo'=>'G'],
['codigo'=>'31200','nombre'=>'Alimentos para Animales','tipo'=>'G'],
['codigo'=>'31300','nombre'=>'Productos Agrícolas, Pecuarios y Forestales','tipo'=>'G'],
['codigo'=>'32000','nombre'=>'Productos de Papel, Cartón e Impresos','tipo'=>'G'],
['codigo'=>'32100','nombre'=>'Papel','tipo'=>'G'],
['codigo'=>'32200','nombre'=>'Productos de Artes Gráficas','tipo'=>'G'],
['codigo'=>'32300','nombre'=>'Libros, Manuales y Revistas','tipo'=>'G'],
['codigo'=>'32400','nombre'=>'Textos de Enseñanza','tipo'=>'G'],
['codigo'=>'32500','nombre'=>'Periódicos y Boletines','tipo'=>'G'],
['codigo'=>'33000','nombre'=>'Textiles y Vestuario','tipo'=>'G'],
['codigo'=>'33100','nombre'=>'Hilados, Telas, Fibras y Algodón','tipo'=>'G'],
['codigo'=>'33200','nombre'=>'Confecciones Textiles','tipo'=>'G'],
['codigo'=>'33300','nombre'=>'Prendas de Vestir','tipo'=>'G'],
['codigo'=>'33400','nombre'=>'Calzados','tipo'=>'G'],
['codigo'=>'34000','nombre'=>'Combustibles, Productos Químicos, Farmacéuticos y Otras Fuentes de Energía','tipo'=>'G'],
['codigo'=>'34100','nombre'=>'Combustibles, Lubricantes, Derivados y otras Fuentes de Energía','tipo'=>'G'],
['codigo'=>'34110','nombre'=>'Combustibles, Lubricantes y Derivados para consumo','tipo'=>'G'],
['codigo'=>'34120','nombre'=>'Combustibles, Lubricantes y Derivados para comercialización','tipo'=>'G'],
['codigo'=>'34130','nombre'=>'Energía Eléctrica para Comercialización','tipo'=>'G'],
['codigo'=>'34200','nombre'=>'Productos Químicos y Farmacéuticos','tipo'=>'G'],
['codigo'=>'34300','nombre'=>'Llantas y Neumáticos','tipo'=>'G'],
['codigo'=>'34400','nombre'=>'Productos de Cuero y Caucho','tipo'=>'G'],
['codigo'=>'34500','nombre'=>'Productos de Minerales no Metálicos y Plásticos','tipo'=>'G'],
['codigo'=>'34600','nombre'=>'Productos Metálicos','tipo'=>'G'],
['codigo'=>'34700','nombre'=>'Minerales','tipo'=>'G'],
['codigo'=>'34800','nombre'=>'Herramientas Menores','tipo'=>'G'],
['codigo'=>'34900','nombre'=>'Material y Equipo Militar','tipo'=>'G'],
['codigo'=>'39000','nombre'=>'Productos Varios','tipo'=>'G'],
['codigo'=>'39100','nombre'=>'Material de Limpieza e Higiene','tipo'=>'G'],
['codigo'=>'39200','nombre'=>'Material Deportivo y Recreativo','tipo'=>'G'],
['codigo'=>'39300','nombre'=>'Utensilios de Cocina y Comedor','tipo'=>'G'],
['codigo'=>'39400','nombre'=>'Instrumental Menor Médico-Quirúrgico','tipo'=>'G'],
['codigo'=>'39500','nombre'=>'Útiles de Escritorio y Oficina','tipo'=>'G'],
['codigo'=>'39600','nombre'=>'Útiles Educacionales, Culturales y de Capacitación','tipo'=>'G'],
['codigo'=>'39700','nombre'=>'Útiles y Materiales Eléctricos','tipo'=>'G'],
['codigo'=>'39800','nombre'=>'Otros Repuestos y Accesorios','tipo'=>'G'],
['codigo'=>'39900','nombre'=>'Otros Materiales y Suministros','tipo'=>'G'],
['codigo'=>'39910','nombre'=>'Acuñación de Monedas e Impresión de Billetes','tipo'=>'G'],
['codigo'=>'39911','nombre'=>'Acuñación de monedas','tipo'=>'G'],
['codigo'=>'39912','nombre'=>'Impresión de billetes','tipo'=>'G'],
['codigo'=>'39990','nombre'=>'Otros Materiales y Suministros','tipo'=>'G'],
['codigo'=>'40000','nombre'=>'ACTIVOS REALES','tipo'=>'G'],
['codigo'=>'41000','nombre'=>'Inmobiliarios','tipo'=>'G'],
['codigo'=>'41100','nombre'=>'Edificios','tipo'=>'G'],
['codigo'=>'41200','nombre'=>'Tierras y Terrenos','tipo'=>'G'],
['codigo'=>'41300','nombre'=>'Otras Adquisiciones','tipo'=>'G'],
['codigo'=>'42000','nombre'=>'Construcciones','tipo'=>'G'],
['codigo'=>'42200','nombre'=>'Construcciones y Mejoras de Bienes Públicos Nacionales de Dominio Privado','tipo'=>'G'],
['codigo'=>'42210','nombre'=>'Construcciones y Mejoras de Viviendas','tipo'=>'G'],
['codigo'=>'42220','nombre'=>'Construcciones y Mejoras para Defensa y Seguridad','tipo'=>'G'],
['codigo'=>'42230','nombre'=>'Otras Construcciones y Mejoras de Bienes Públicos de Dominio Privado','tipo'=>'G'],
['codigo'=>'42240','nombre'=>'Supervisión de Construcciones y Mejoras de Bienes Públicos de Dominio Privado','tipo'=>'G'],
['codigo'=>'42300','nombre'=>'Construcciones y Mejoras de Bienes Nacionales de Dominio Público','tipo'=>'G'],
['codigo'=>'42310','nombre'=>'Construcciones y Mejoras de Bienes de Dominio Público','tipo'=>'G'],
['codigo'=>'42320','nombre'=>'Supervisión de Construcciones y Mejoras de Bienes de Dominio Público','tipo'=>'G'],
['codigo'=>'43000','nombre'=>'Maquinaria y Equipo','tipo'=>'G'],
['codigo'=>'43100','nombre'=>'Equipo de Oficina y Muebles','tipo'=>'G'],
['codigo'=>'43110','nombre'=>'Equipo de Oficina y Muebles','tipo'=>'G'],
['codigo'=>'43120','nombre'=>'Equipo de Computación','tipo'=>'G'],
['codigo'=>'43200','nombre'=>'Maquinaria y Equipo de Producción','tipo'=>'G'],
['codigo'=>'43300','nombre'=>'Equipo de Transporte, Tracción y Elevación','tipo'=>'G'],
['codigo'=>'43310','nombre'=>'Vehículos Livianos para Funciones Administrativas','tipo'=>'G'],
['codigo'=>'43320','nombre'=>'Vehículos Livianos para Proyectos de Inversión Pública','tipo'=>'G'],
['codigo'=>'43330','nombre'=>'Maquinaria y Equipo de Transporte','tipo'=>'G'],
['codigo'=>'43340','nombre'=>'Equipo de Elevación','tipo'=>'G'],
['codigo'=>'43400','nombre'=>'Equipo Médico y de Laboratorio','tipo'=>'G'],
['codigo'=>'43500','nombre'=>'Equipo de Comunicación','tipo'=>'G'],
['codigo'=>'43600','nombre'=>'Equipo Educacional y Recreativo','tipo'=>'G'],
['codigo'=>'43700','nombre'=>'Otra Maquinaria y Equipo','tipo'=>'G'],
['codigo'=>'46000','nombre'=>'Estudios y Proyectos para Inversión','tipo'=>'G'],
['codigo'=>'46100','nombre'=>'Para Construcciones de Bienes Públicos de Dominio Privado','tipo'=>'G'],
['codigo'=>'46110','nombre'=>'Consultoría por Producto para Construcciones de Bienes Públicos de Dominio Privado','tipo'=>'G'],
['codigo'=>'46120','nombre'=>'Consultoría de Línea para Construcciones de Bienes Públicos de Dominio Privado','tipo'=>'G'],
['codigo'=>'46200','nombre'=>'Para Construcciones de Bienes de Dominio Público','tipo'=>'G'],
['codigo'=>'46210','nombre'=>'Consultoría por Producto para Construcciones de Bienes Públicos de Dominio Público','tipo'=>'G'],
['codigo'=>'46220','nombre'=>'Consultoría de Línea para Construcciones de Bienes Públicos de Dominio Público','tipo'=>'G'],
['codigo'=>'46300','nombre'=>'Consultoría para capacitación, transferencia de tecnología y organización para procesos productivos, en proyectos de Inversión específicos.','tipo'=>'G'],
['codigo'=>'46310','nombre'=>'Consultoría por Producto','tipo'=>'G'],
['codigo'=>'46320','nombre'=>'Consultoría de Línea','tipo'=>'G'],
['codigo'=>'49000','nombre'=>'Otros Activos','tipo'=>'G'],
['codigo'=>'49100','nombre'=>'Activos Intangibles','tipo'=>'G'],
['codigo'=>'49300','nombre'=>'Semovientes y Otros Animales','tipo'=>'G'],
['codigo'=>'49400','nombre'=>'Activos Museológicos y Culturales','tipo'=>'G'],
['codigo'=>'49900','nombre'=>'Otros','tipo'=>'G'],
['codigo'=>'50000','nombre'=>'ACTIVOS FINANCIEROS','tipo'=>'G'],
['codigo'=>'51000','nombre'=>'Compra de Acciones, Participaciones de Capital e Inversiones','tipo'=>'G'],
['codigo'=>'51100','nombre'=>'Acciones y Participaciones de Capital en Empresas Privadas Nacionales','tipo'=>'G'],
['codigo'=>'51200','nombre'=>'Acciones y Participaciones de Capital en Empresas Públicas Nacionales','tipo'=>'G'],
['codigo'=>'51300','nombre'=>'Acciones y Participaciones de Capital en Empresas Públicas Territoriales','tipo'=>'G'],
['codigo'=>'51310','nombre'=>'Del Gobierno Autónomo Departamental','tipo'=>'G'],
['codigo'=>'51320','nombre'=>'Del Gobierno Autónomo Municipal','tipo'=>'G'],
['codigo'=>'51330','nombre'=>'Del Gobierno Autónomo Indígena Originario Campesino','tipo'=>'G'],
['codigo'=>'51340','nombre'=>'Del Gobierno Autónomo Regional','tipo'=>'G'],
['codigo'=>'51500','nombre'=>'Acciones y Participaciones de Capital en Instituciones Públicas Financieras No Bancarias','tipo'=>'G'],
['codigo'=>'51600','nombre'=>'Acciones y Participaciones de Capital en Instituciones Públicas Financieras Bancarias','tipo'=>'G'],
['codigo'=>'51700','nombre'=>'Acciones y Participaciones de Capital en Organismos Internacionales','tipo'=>'G'],
['codigo'=>'51800','nombre'=>'Otras Acciones y Participaciones de Capital en el Exterior','tipo'=>'G'],
['codigo'=>'51900','nombre'=>'Inversiones en el Exterior','tipo'=>'G'],
['codigo'=>'52000','nombre'=>'Concesión de Préstamos a Corto Plazo al Sector Público No Financiero','tipo'=>'G'],
['codigo'=>'52100','nombre'=>'Concesión de Préstamos a Corto Plazo a los Órganos del Estado Plurinacional','tipo'=>'G'],
['codigo'=>'52200','nombre'=>'Concesión de Préstamos a Corto Plazo a Instituciones Públicas Descentralizadas','tipo'=>'G'],
['codigo'=>'52400','nombre'=>'Concesión de Préstamos a Corto Plazo a Entidades Territoriales Autónomas','tipo'=>'G'],
['codigo'=>'52410','nombre'=>'Gobierno Autónomo Departamental','tipo'=>'G'],
['codigo'=>'52420','nombre'=>'Gobierno Autónomo Municipal','tipo'=>'G'],
['codigo'=>'52430','nombre'=>'Gobierno Autónomo Indígena Originario Campesino','tipo'=>'G'],
['codigo'=>'52440','nombre'=>'Gobierno Autónomo Regional','tipo'=>'G'],
['codigo'=>'52600','nombre'=>'Concesión de Préstamos a Corto Plazo a Instituciones de Seguridad Social','tipo'=>'G'],
['codigo'=>'52700','nombre'=>'Concesión de Préstamos a Corto Plazo a Empresas Públicas Nacionales','tipo'=>'G'],
['codigo'=>'52800','nombre'=>'Concesión de Préstamos a Corto Plazo a Empresas Públicas Territoriales','tipo'=>'G'],
['codigo'=>'52810','nombre'=>'Del Gobierno Autónomo Departamental','tipo'=>'G'],
['codigo'=>'52820','nombre'=>'Del Gobierno Autónomo Municipal','tipo'=>'G'],
['codigo'=>'52830','nombre'=>'Del Gobierno Autónomo Indígena Originario Campesino','tipo'=>'G'],
['codigo'=>'52840','nombre'=>'Del Gobierno Autónomo Regional','tipo'=>'G'],
['codigo'=>'53000','nombre'=>'Concesión de Préstamos a Largo Plazo al Sector Público No Financiero','tipo'=>'G'],
['codigo'=>'53100','nombre'=>'Concesión de Préstamos a Largo Plazo a los Órganos del Estado Plurinacional','tipo'=>'G'],
['codigo'=>'53200','nombre'=>'Concesión de Préstamos a Largo Plazo a Instituciones Públicas Descentralizadas','tipo'=>'G'],
['codigo'=>'53400','nombre'=>'Concesión de Préstamos a Largo Plazo a Entidades Territoriales Autónomas','tipo'=>'G'],
['codigo'=>'53410','nombre'=>'Gobierno Autónomo Departamental','tipo'=>'G'],
['codigo'=>'53420','nombre'=>'Gobierno Autónomo Municipal','tipo'=>'G'],
['codigo'=>'53430','nombre'=>'Gobierno Autónomo Indígena Originario Campesino','tipo'=>'G'],
['codigo'=>'53440','nombre'=>'Gobierno Autónomo Regional','tipo'=>'G'],
['codigo'=>'53600','nombre'=>'Concesión de Préstamos a Largo Plazo a Instituciones de Seguridad Social','tipo'=>'G'],
['codigo'=>'53700','nombre'=>'Concesión de Préstamos a Largo Plazo a Empresas Públicas Nacionales','tipo'=>'G'],
['codigo'=>'53800','nombre'=>'Concesión de Préstamos a Largo Plazo a Empresas Públicas Territoriales','tipo'=>'G'],
['codigo'=>'53810','nombre'=>'Del Gobierno Autónomo Departamental','tipo'=>'G'],
['codigo'=>'53820','nombre'=>'Del Gobierno Autónomo Municipal','tipo'=>'G'],
['codigo'=>'53830','nombre'=>'Del Gobierno Autónomo Indígena Originario Campesino','tipo'=>'G'],
['codigo'=>'53840','nombre'=>'Del Gobierno Autónomo Regional','tipo'=>'G'],
['codigo'=>'54000','nombre'=>'Concesión de Préstamos al Sector Público Financiero y a los Sectores Privado y del Exterior','tipo'=>'G'],
['codigo'=>'54100','nombre'=>'Concesión de Préstamos a Corto Plazo a Instituciones Públicas Financieras No Bancarias','tipo'=>'G'],
['codigo'=>'54200','nombre'=>'Concesión de Préstamos a Corto Plazo a Instituciones Públicas Financieras Bancarias','tipo'=>'G'],
['codigo'=>'54300','nombre'=>'Concesión de Préstamos a Corto Plazo al Sector Privado','tipo'=>'G'],
['codigo'=>'54400','nombre'=>'Concesión de Préstamos a Corto Plazo al Exterior','tipo'=>'G'],
['codigo'=>'54600','nombre'=>'Concesión de Préstamos a Largo Plazo a Instituciones Públicas Financieras No Bancarias','tipo'=>'G'],
['codigo'=>'54700','nombre'=>'Concesión de Préstamos a Largo Plazo a Instituciones Públicas Financieras Bancarias','tipo'=>'G'],
['codigo'=>'54800','nombre'=>'Concesión de Préstamos a Largo Plazo al Sector Privado','tipo'=>'G'],
['codigo'=>'54900','nombre'=>'Concesión de Préstamos a Largo Plazo al Exterior','tipo'=>'G'],
['codigo'=>'55000','nombre'=>'Compra de Títulos y Valores','tipo'=>'G'],
['codigo'=>'55100','nombre'=>'Títulos y Valores a Corto Plazo','tipo'=>'G'],
['codigo'=>'55110','nombre'=>'Letras del Tesoro','tipo'=>'G'],
['codigo'=>'55120','nombre'=>'Bonos del Tesoro','tipo'=>'G'],
['codigo'=>'55130','nombre'=>'Otros','tipo'=>'G'],
['codigo'=>'55200','nombre'=>'Títulos y Valores a Largo Plazo','tipo'=>'G'],
['codigo'=>'55210','nombre'=>'Letras del Tesoro','tipo'=>'G'],
['codigo'=>'55220','nombre'=>'Bonos del Tesoro','tipo'=>'G'],
['codigo'=>'55230','nombre'=>'Otros','tipo'=>'G'],
['codigo'=>'56000','nombre'=>'Constitución de Fideicomisos y Servicios Financieros','tipo'=>'G'],
['codigo'=>'56100','nombre'=>'Colocación de Fondos en Fideicomiso','tipo'=>'G'],
['codigo'=>'56200','nombre'=>'Concesiones de Recursos de Fideicomisos','tipo'=>'G'],
['codigo'=>'56300','nombre'=>'Colocación de Fondos por Servicios Financieros','tipo'=>'G'],
['codigo'=>'57000','nombre'=>'Incremento de Disponibilidades','tipo'=>'G'],
['codigo'=>'57100','nombre'=>'Incremento de Caja y Bancos','tipo'=>'G'],
['codigo'=>'57200','nombre'=>'Incremento de Inversiones Temporales','tipo'=>'G'],
['codigo'=>'58000','nombre'=>'Incremento de Cuentas y Documentos por Cobrar y Otros Activos Financieros','tipo'=>'G'],
['codigo'=>'58100','nombre'=>'Incremento de Cuentas por Cobrar a Corto Plazo','tipo'=>'G'],
['codigo'=>'58200','nombre'=>'Incremento de Documentos por Cobrar y Otros Activos Financieros a Corto Plazo','tipo'=>'G'],
['codigo'=>'58210','nombre'=>'Incremento de Documentos por Cobrar a Corto Plazo','tipo'=>'G'],
['codigo'=>'58220','nombre'=>'Incremento de Otros Activos Financieros a Corto Plazo','tipo'=>'G'],
['codigo'=>'58300','nombre'=>'Incremento de Cuentas por Cobrar a Largo Plazo','tipo'=>'G'],
['codigo'=>'58400','nombre'=>'Incremento de Documentos por Cobrar y Otros Activos Financieros a Largo Plazo','tipo'=>'G'],
['codigo'=>'58410','nombre'=>'Incremento de Documentos por Cobrar a Largo Plazo','tipo'=>'G'],
['codigo'=>'58420','nombre'=>'Incremento de Otros Activos Financieros a largo Plazo','tipo'=>'G'],
['codigo'=>'59000','nombre'=>'Afectaciones al Tesoro General de la Nación','tipo'=>'G'],
['codigo'=>'59100','nombre'=>'Afectaciones al Tesoro General de la Nación','tipo'=>'G'],
['codigo'=>'60000','nombre'=>'SERVICIO DE LA DEUDA PUBLICA Y DISMINUCION DE OTROS PASIVOS','tipo'=>'G'],
['codigo'=>'61000','nombre'=>'Servicio de la Deuda Pública Interna','tipo'=>'G'],
['codigo'=>'61100','nombre'=>'Amortización de la Deuda Pública Interna a Corto Plazo','tipo'=>'G'],
['codigo'=>'61200','nombre'=>'Intereses de la Deuda Pública Interna a Corto Plazo','tipo'=>'G'],
['codigo'=>'61300','nombre'=>'Comisiones y Otros Gastos de la Deuda Pública Interna a Corto Plazo','tipo'=>'G'],
['codigo'=>'61400','nombre'=>'Intereses por Mora y Multas de la Deuda Pública Interna a Corto Plazo','tipo'=>'G'],
['codigo'=>'61600','nombre'=>'Amortización de la Deuda Pública Interna a Largo Plazo','tipo'=>'G'],
['codigo'=>'61700','nombre'=>'Intereses de la Deuda Pública Interna a Largo Plazo','tipo'=>'G'],
['codigo'=>'61800','nombre'=>'Comisiones y Otros Gastos de la Deuda Pública Interna a Largo Plazo','tipo'=>'G'],
['codigo'=>'61900','nombre'=>'Intereses por Mora y Multas de la Deuda Pública Interna a Largo Plazo','tipo'=>'G'],
['codigo'=>'62000','nombre'=>'Servicio de la Deuda Pública Externa','tipo'=>'G'],
['codigo'=>'62100','nombre'=>'Amortización de la Deuda Pública Externa a Corto Plazo','tipo'=>'G'],
['codigo'=>'62200','nombre'=>'Intereses de la Deuda Pública Externa a Corto Plazo','tipo'=>'G'],
['codigo'=>'62300','nombre'=>'Comisiones y Otros Gastos de la Deuda Pública Externa a Corto Plazo','tipo'=>'G'],
['codigo'=>'62400','nombre'=>'Intereses por Mora y Multas de la Deuda Pública Externa a Corto Plazo','tipo'=>'G'],
['codigo'=>'62600','nombre'=>'Amortización de la Deuda Pública Externa a Largo Plazo','tipo'=>'G'],
['codigo'=>'62700','nombre'=>'Intereses de la Deuda Pública Externa a Largo Plazo','tipo'=>'G'],
['codigo'=>'62800','nombre'=>'Comisiones y Otros Gastos de la Deuda Pública Externa a Largo Plazo','tipo'=>'G'],
['codigo'=>'62900','nombre'=>'Intereses por Mora y Multas de la Deuda Pública Externa a Largo Plazo','tipo'=>'G'],
['codigo'=>'63000','nombre'=>'Disminución de Cuentas por Pagar a Corto Plazo','tipo'=>'G'],
['codigo'=>'63100','nombre'=>'Disminución de Cuentas por Pagar a Corto Plazo por Deudas Comerciales con Proveedores','tipo'=>'G'],
['codigo'=>'63200','nombre'=>'Disminución de Cuentas por Pagar a Corto Plazo con Contratistas','tipo'=>'G'],
['codigo'=>'63300','nombre'=>'Disminución de Cuentas por Pagar a Corto Plazo por Sueldos y Jornales','tipo'=>'G'],
['codigo'=>'63400','nombre'=>'Disminución de Cuentas por Pagar a Corto Plazo por Aportes Patronales','tipo'=>'G'],
['codigo'=>'63500','nombre'=>'Disminución de Cuentas por Pagar a Corto Plazo por Retenciones','tipo'=>'G'],
['codigo'=>'63600','nombre'=>'Disminución de Cuentas por Pagar a Corto Plazo por Impuestos, Regalías y Tasas','tipo'=>'G'],
['codigo'=>'63700','nombre'=>'Disminución de Cuentas por Pagar a Corto Plazo por Jubilaciones y Pensiones','tipo'=>'G'],
['codigo'=>'63800','nombre'=>'Disminución de Cuentas por Pagar a Corto Plazo por Intereses','tipo'=>'G'],
['codigo'=>'63900','nombre'=>'Disminución de Otros Pasivos y Otras Cuentas por Pagar a Corto Plazo','tipo'=>'G'],
['codigo'=>'64000','nombre'=>'Disminución de Cuentas por Pagar a Largo Plazo','tipo'=>'G'],
['codigo'=>'64100','nombre'=>'Disminución de Cuentas por Pagar a Largo Plazo por Deudas Comerciales','tipo'=>'G'],
['codigo'=>'64200','nombre'=>'Disminución de Otras Cuentas por Pagar a Largo Plazo','tipo'=>'G'],
['codigo'=>'65000','nombre'=>'Gastos Devengados No Pagados - TGN','tipo'=>'G'],
['codigo'=>'65100','nombre'=>'Gastos Devengados No Pagados por Servicios Personales','tipo'=>'G'],
['codigo'=>'65200','nombre'=>'Gastos Devengados No Pagados por Servicios No Personales, Materiales y Suministros, Activos Reales y Financieros','tipo'=>'G'],
['codigo'=>'65210','nombre'=>'Gastos Devengados No Pagados por Servicios No Personales','tipo'=>'G'],
['codigo'=>'65220','nombre'=>'Gastos Devengados No Pagados por Materiales y Suministros','tipo'=>'G'],
['codigo'=>'65230','nombre'=>'Gastos Devengados No Pagados por Activos Reales','tipo'=>'G'],
['codigo'=>'65240','nombre'=>'Gastos Devengados No Pagados por Activos Financieros','tipo'=>'G'],
['codigo'=>'65300','nombre'=>'Gastos Devengados No Pagados por Transferencias','tipo'=>'G'],
['codigo'=>'65400','nombre'=>'Gastos Devengados No Pagados por Retenciones','tipo'=>'G'],
['codigo'=>'65500','nombre'=>'Gastos Devengados No Pagados por Intereses Deuda Pública Interna','tipo'=>'G'],
['codigo'=>'65600','nombre'=>'Gastos Devengados No Pagados por Intereses Deuda Pública Externa','tipo'=>'G'],
['codigo'=>'65700','nombre'=>'Gastos Devengados No Pagados por Comisiones Deuda Pública Interna','tipo'=>'G'],
['codigo'=>'65800','nombre'=>'Gastos Devengados No Pagados por Comisiones Deuda Pública Externa','tipo'=>'G'],
['codigo'=>'65900','nombre'=>'Otros Gastos Devengados No Pagados','tipo'=>'G'],
['codigo'=>'66000','nombre'=>'Gastos Devengados No Pagados - Otras Fuentes','tipo'=>'G'],
['codigo'=>'66100','nombre'=>'Gastos Devengados No Pagados por Servicios Personales','tipo'=>'G'],
['codigo'=>'66200','nombre'=>'Gastos Devengados No Pagados por Servicios No Personales, Materiales y Suministros, Activos Reales y Financieros','tipo'=>'G'],
['codigo'=>'66210','nombre'=>'Gastos Devengados No Pagados por Servicios No Personales','tipo'=>'G'],
['codigo'=>'66220','nombre'=>'Gastos Devengados No Pagados por Materiales y Suministros','tipo'=>'G'],
['codigo'=>'66230','nombre'=>'Gastos Devengados No Pagados por Activos Reales','tipo'=>'G'],
['codigo'=>'66240','nombre'=>'Gastos Devengados No Pagados por Activos Financieros','tipo'=>'G'],
['codigo'=>'66300','nombre'=>'Gastos Devengados No Pagados por Transferencias','tipo'=>'G'],
['codigo'=>'66400','nombre'=>'Gastos Devengados No pagados por Retenciones','tipo'=>'G'],
['codigo'=>'66900','nombre'=>'Otros Gastos No Pagados','tipo'=>'G'],
['codigo'=>'67000','nombre'=>'Obligaciones por Afectaciones al Tesoro General de la Nación','tipo'=>'G'],
['codigo'=>'67100','nombre'=>'Obligaciones por Afectaciones al Tesoro General de la Nación','tipo'=>'G'],
['codigo'=>'68000','nombre'=>'Disminución de Otros Pasivos','tipo'=>'G'],
['codigo'=>'68200','nombre'=>'Pago de Beneficios Sociales','tipo'=>'G'],
['codigo'=>'69000','nombre'=>'Devolución de Fondos -Fideicomisos','tipo'=>'G'],
['codigo'=>'69100','nombre'=>'Devolución de Fondos - Fideicomiso de Corto Plazo','tipo'=>'G'],
['codigo'=>'69200','nombre'=>'Devolución de Fondos - Fideicomiso de Largo Plazo','tipo'=>'G'],
['codigo'=>'70000','nombre'=>'TRANSFERENCIAS','tipo'=>'G'],
['codigo'=>'71000','nombre'=>'Transferencias Corrientes al Sector Privado','tipo'=>'G'],
['codigo'=>'71100','nombre'=>'Pensiones y Jubilaciones','tipo'=>'G'],
['codigo'=>'71200','nombre'=>'Becas','tipo'=>'G'],
['codigo'=>'71210','nombre'=>'Becas de Estudios Otorgadas a los Servidores Públicos','tipo'=>'G'],
['codigo'=>'71220','nombre'=>'Becas de Estudios Otorgadas a los Estudiantes Universitarios','tipo'=>'G'],
['codigo'=>'71230','nombre'=>'Becas de Estudios Otorgadas a Particulares','tipo'=>'G'],
['codigo'=>'71300','nombre'=>'Donaciones, Ayudas Sociales y Premios a Personas','tipo'=>'G'],
['codigo'=>'71600','nombre'=>'Subsidios y Donaciones a Personas e Instituciones Privadas sin Fines de Lucro','tipo'=>'G'],
['codigo'=>'71610','nombre'=>'A Personas e Instituciones Privadas sin Fines de Lucro','tipo'=>'G'],
['codigo'=>'71630','nombre'=>'Otros de Carácter Social Establecidos por Norma Legal','tipo'=>'G'],
['codigo'=>'71700','nombre'=>'Subvenciones Económicas a Empresas','tipo'=>'G'],
['codigo'=>'71800','nombre'=>'Pensiones Vitalicias','tipo'=>'G'],
['codigo'=>'71900','nombre'=>'Transferencias por las Compras de Control Tributario','tipo'=>'G'],
['codigo'=>'72000','nombre'=>'Transferencias Corrientes al Sector Público No Financiero por Participación en Tributos','tipo'=>'G'],
['codigo'=>'72200','nombre'=>'Transferencias Corrientes a Instituciones Públicas Descentralizadas, Universidades Públicas por Participación en Tributos','tipo'=>'G'],
['codigo'=>'72400','nombre'=>'Transferencias Corrientes al Gobierno Autónomo Departamental por Participación en Tributos','tipo'=>'G'],
['codigo'=>'72410','nombre'=>'Para Educación','tipo'=>'G'],
['codigo'=>'72420','nombre'=>'Otras','tipo'=>'G'],
['codigo'=>'72500','nombre'=>'Transferencias Corrientes a los Gobiernos Autónomos Municipales e Indígena Originario','tipo'=>'G'],
['codigo'=>'72510','nombre'=>'Para Salud','tipo'=>'G'],
['codigo'=>'72520','nombre'=>'Otras','tipo'=>'G'],
['codigo'=>'73000','nombre'=>'Transferencias Corrientes al Sector Público No Financiero por Subsidios o Subvenciones','tipo'=>'G'],
['codigo'=>'73100','nombre'=>'Transferencias Corrientes al Órgano Ejecutivo del Estado Plurinacional por Subsidios o Subvenciones','tipo'=>'G'],
['codigo'=>'73200','nombre'=>'TTransferencias Corrientes a los Órganos Legislativo, Judicial y Electoral, Entidades de Control y Defensa, Descentralizadas y Universidades por Subsidios o Subvenciones','tipo'=>'G'],
['codigo'=>'73300','nombre'=>'Transferencias Corrientes del Fondo Compensatorio Nacional de Salud','tipo'=>'G'],
['codigo'=>'73400','nombre'=>'Transferencias Corrientes a Entidades Territoriales Autónomas por Subsidios o Subvenciones','tipo'=>'G'],
['codigo'=>'73410','nombre'=>'Gobierno Autónomo Departamental','tipo'=>'G'],
['codigo'=>'73420','nombre'=>'Gobierno Autónomo Municipal','tipo'=>'G'],
['codigo'=>'73430','nombre'=>'Gobierno Autónomo Indígena Originario Campesino','tipo'=>'G'],
['codigo'=>'73440','nombre'=>'Gobierno Autónomo Regional','tipo'=>'G'],
['codigo'=>'73600','nombre'=>'Transferencias Corrientes a Instituciones de Seguridad Social por Subsidios o Subvenciones','tipo'=>'G'],
['codigo'=>'73700','nombre'=>'Transferencias Corrientes a Empresas Públicas Nacionales por Subsidios o Subvenciones','tipo'=>'G'],
['codigo'=>'73800','nombre'=>'Transferencias Corrientes a Empresas Públicas de las Entidades Territoriales Autónomas por Subsidios o Subvenciones','tipo'=>'G'],
['codigo'=>'73810','nombre'=>'Empresas Públicas Departamentales','tipo'=>'G'],
['codigo'=>'73820','nombre'=>'Empresas Públicas Municipales','tipo'=>'G'],
['codigo'=>'73830','nombre'=>'Empresas Públicas Indígenas Originarias Campesinas','tipo'=>'G'],
['codigo'=>'73840','nombre'=>'Empresa Públicas Regionales','tipo'=>'G'],
['codigo'=>'74000','nombre'=>'Transferencias Corrientes al Sector Público Financiero','tipo'=>'G'],
['codigo'=>'74100','nombre'=>'Transferencias Corrientes a Instituciones Públicas Financieras No Bancarias','tipo'=>'G'],
['codigo'=>'74200','nombre'=>'Transferencias Corrientes a Instituciones Públicas Financieras Bancarias','tipo'=>'G'],
['codigo'=>'75000','nombre'=>'Transferencias de Capital al Sector Privado','tipo'=>'G'],
['codigo'=>'75100','nombre'=>'Transferencias de Capital a Personas','tipo'=>'G'],
['codigo'=>'75200','nombre'=>'Transferencias de Capital a Instituciones Privadas sin Fines de Lucro','tipo'=>'G'],
['codigo'=>'75210','nombre'=>'A Instituciones Privadas sin Fines de Lucro','tipo'=>'G'],
['codigo'=>'75220','nombre'=>'Otras de carácter económico - productivo','tipo'=>'G'],
['codigo'=>'75300','nombre'=>'Transferencias de Capital a Empresas Privadas','tipo'=>'G'],
['codigo'=>'77000','nombre'=>'Transferencias de Capital al Sector Público No Financiero por Subsidios o Subvenciones','tipo'=>'G'],
['codigo'=>'77100','nombre'=>'Transferencias de Capital al Órgano Ejecutivo del Estado Plurinacional por Subsidios o Subvenciones','tipo'=>'G'],
['codigo'=>'77200','nombre'=>'Transferencias de Capital a los Órganos Legislativo, Judicial y Electoral, Entidades de Control y Defensa, Descentralizadas y Universidades por Subsidios o Subvenciones','tipo'=>'G'],
['codigo'=>'77400','nombre'=>'Transferencias de Capital a las Entidades Territoriales Autónomas por Subsidios o Subvenciones','tipo'=>'G'],
['codigo'=>'77410','nombre'=>'Al Gobierno Autónomo Departamental','tipo'=>'G'],
['codigo'=>'77440','nombre'=>'Al Gobierno Autónomo Regional','tipo'=>'G'],
['codigo'=>'77500','nombre'=>'Transferencias de Capital a los Gobiernos Autónomos Municipales e Indígena Originario Campesino por Subsidios o Subvenciones','tipo'=>'G'],
['codigo'=>'77510','nombre'=>'Diálogo Nacional 2000','tipo'=>'G'],
['codigo'=>'77511','nombre'=>'Para Salud','tipo'=>'G'],
['codigo'=>'77512','nombre'=>'Para Educación','tipo'=>'G'],
['codigo'=>'77513','nombre'=>'Para Infraestructura','tipo'=>'G'],
['codigo'=>'77520','nombre'=>'Por Patentes Petroleras','tipo'=>'G'],
['codigo'=>'77530','nombre'=>'Otras','tipo'=>'G'],
['codigo'=>'77600','nombre'=>'Transferencias de Capital a Instituciones de Seguridad Social por Subsidios o Subvenciones','tipo'=>'G'],
['codigo'=>'77700','nombre'=>'Transferencias de Capital a Empresas Públicas Nacionales por Subsidios o Subvenciones','tipo'=>'G'],
['codigo'=>'77800','nombre'=>'Transferencias de Capital a Empresas Públicas de las Entidades Territoriales Autónomas','tipo'=>'G'],
['codigo'=>'77810','nombre'=>'A Empresas Públicas Departamentales','tipo'=>'G'],
['codigo'=>'77820','nombre'=>'A Empresas Públicas Municipales','tipo'=>'G'],
['codigo'=>'77830','nombre'=>'A Empresas Públicas Indígenas Originarias y Campesinas','tipo'=>'G'],
['codigo'=>'77840','nombre'=>'A Empresas Públicas Regionales','tipo'=>'G'],
['codigo'=>'78000','nombre'=>'Transferencias de Capital al Sector Público Financiero','tipo'=>'G'],
['codigo'=>'78100','nombre'=>'Transferencias de Capital a Instituciones Públicas Financieras No Bancarias','tipo'=>'G'],
['codigo'=>'78200','nombre'=>'Transferencias de Capital a Instituciones Públicas Financieras Bancarias','tipo'=>'G'],
['codigo'=>'79000','nombre'=>'Transferencias al Exterior','tipo'=>'G'],
['codigo'=>'79100','nombre'=>'Transferencias Corrientes a Gobiernos Extranjeros y Organismos Internacionales por Cuotas Regulares','tipo'=>'G'],
['codigo'=>'79200','nombre'=>'Transferencias Corrientes a Gobiernos Extranjeros y Organismos Internacionales por Cuotas Extraordinarias','tipo'=>'G'],
['codigo'=>'79300','nombre'=>'Otras Transferencias Corrientes al Exterior','tipo'=>'G'],
['codigo'=>'79310','nombre'=>'Transferencias al Exterior en Efectivo','tipo'=>'G'],
['codigo'=>'79320','nombre'=>'Transferencias al Exterior en Especie','tipo'=>'G'],
['codigo'=>'79400','nombre'=>'Transferencias de Capital al Exterior','tipo'=>'G'],
['codigo'=>'80000','nombre'=>'IMPUESTOS, REGALIAS Y TASAS','tipo'=>'G'],
['codigo'=>'81000','nombre'=>'Renta Interna','tipo'=>'G'],
['codigo'=>'81100','nombre'=>'Impuesto sobre las Utilidades de las Empresas','tipo'=>'G'],
['codigo'=>'81200','nombre'=>'Impuesto a las Transacciones','tipo'=>'G'],
['codigo'=>'81300','nombre'=>'Impuesto al Valor Agregado Mercado Interno','tipo'=>'G'],
['codigo'=>'81400','nombre'=>'Impuesto al Valor Agregado Importaciones','tipo'=>'G'],
['codigo'=>'81500','nombre'=>'Impuesto a los Consumos Específicos Mercado Interno','tipo'=>'G'],
['codigo'=>'81600','nombre'=>'Impuesto a los Consumos Específicos Importaciones','tipo'=>'G'],
['codigo'=>'81700','nombre'=>'Impuesto Especial a los Hidrocarburos y sus Derivados Mercado Interno','tipo'=>'G'],
['codigo'=>'81800','nombre'=>'Impuesto Especial a los Hidrocarburos y sus Derivados Importación','tipo'=>'G'],
['codigo'=>'81900','nombre'=>'Otros Impuestos','tipo'=>'G'],
['codigo'=>'81910','nombre'=>'Impuesto a las Salidas Aéreas al Exterior','tipo'=>'G'],
['codigo'=>'81950','nombre'=>'Impuesto a la Transmisión Gratuita de Bienes- ITGB','tipo'=>'G'],
['codigo'=>'81960','nombre'=>'Impuesto a las Transacciones Financieras - ITF','tipo'=>'G'],
['codigo'=>'81990','nombre'=>'Otros','tipo'=>'G'],
['codigo'=>'82000','nombre'=>'Renta Aduanera','tipo'=>'G'],
['codigo'=>'82100','nombre'=>'Gravamen Arancelario','tipo'=>'G'],
['codigo'=>'83000','nombre'=>'Impuestos Municipales','tipo'=>'G'],
['codigo'=>'83100','nombre'=>'Impuesto a la Propiedad de Bienes','tipo'=>'G'],
['codigo'=>'83110','nombre'=>'Bienes Inmuebles','tipo'=>'G'],
['codigo'=>'83120','nombre'=>'Vehículos Automotores','tipo'=>'G'],
['codigo'=>'83200','nombre'=>'Impuesto a las Transferencias onerosas de bienes inmuebles y vehículos automotores','tipo'=>'G'],
['codigo'=>'83210','nombre'=>'Bienes Inmuebles','tipo'=>'G'],
['codigo'=>'83220','nombre'=>'Vehículos Automotores','tipo'=>'G'],
['codigo'=>'84000','nombre'=>'Regalías','tipo'=>'G'],
['codigo'=>'84100','nombre'=>'Regalías Mineras','tipo'=>'G'],
['codigo'=>'84200','nombre'=>'Regalías por Hidrocarburos','tipo'=>'G'],
['codigo'=>'84230','nombre'=>'6% Participación TGN','tipo'=>'G'],
['codigo'=>'84240','nombre'=>'11% Sobre Producción por Regalías Departamentales','tipo'=>'G'],
['codigo'=>'84250','nombre'=>'1% Sobre Producción para Regalías Compensatoria Departamental','tipo'=>'G'],
['codigo'=>'84300','nombre'=>'Regalías Agropecuarias','tipo'=>'G'],
['codigo'=>'84900','nombre'=>'Otras Regalías','tipo'=>'G'],
['codigo'=>'85000','nombre'=>'Tasas, Multas y Otros','tipo'=>'G'],
['codigo'=>'85100','nombre'=>'Tasas','tipo'=>'G'],
['codigo'=>'85200','nombre'=>'Derechos','tipo'=>'G'],
['codigo'=>'85300','nombre'=>'Contribuciones por Mejoras','tipo'=>'G'],
['codigo'=>'85400','nombre'=>'Multas','tipo'=>'G'],
['codigo'=>'85500','nombre'=>'Intereses Penales','tipo'=>'G'],
['codigo'=>'85900','nombre'=>'Otros','tipo'=>'G'],
['codigo'=>'86000','nombre'=>'Patentes','tipo'=>'G'],
['codigo'=>'86100','nombre'=>'Patentes','tipo'=>'G'],
['codigo'=>'90000','nombre'=>'OTROS GASTOS','tipo'=>'G'],
['codigo'=>'91000','nombre'=>'Intereses de Instituciones Financieras','tipo'=>'G'],
['codigo'=>'91100','nombre'=>'Intereses de Instituciones Públicas Financieras no Bancarias','tipo'=>'G'],
['codigo'=>'91200','nombre'=>'Intereses de Instituciones Públicas Financieras Bancarias','tipo'=>'G'],
['codigo'=>'94000','nombre'=>'Beneficios Sociales y Otros','tipo'=>'G'],
['codigo'=>'94100','nombre'=>'Indemnización','tipo'=>'G'],
['codigo'=>'94200','nombre'=>'Desahucio','tipo'=>'G'],
['codigo'=>'94300','nombre'=>'Otros Beneficios Sociales','tipo'=>'G'],
['codigo'=>'95000','nombre'=>'Contingencias Judiciales','tipo'=>'G'],
['codigo'=>'95100','nombre'=>'Contingencias Judiciales','tipo'=>'G'],
['codigo'=>'96000','nombre'=>'Otras Pérdidas y Devoluciones','tipo'=>'G'],
['codigo'=>'96100','nombre'=>'Pérdidas en Operaciones Cambiarias','tipo'=>'G'],
['codigo'=>'96200','nombre'=>'Devoluciones','tipo'=>'G'],
['codigo'=>'96900','nombre'=>'Otras Pérdidas','tipo'=>'G'],
['codigo'=>'97000','nombre'=>'Comisiones y Bonificaciones','tipo'=>'G'],
['codigo'=>'97100','nombre'=>'Comisiones por Ventas','tipo'=>'G'],
['codigo'=>'97200','nombre'=>'Bonificaciones por Ventas','tipo'=>'G'],
['codigo'=>'98000','nombre'=>'Retiros de Capital','tipo'=>'G'],
['codigo'=>'98100','nombre'=>'Del Sector Público','tipo'=>'G'],
['codigo'=>'98200','nombre'=>'Del Sector Privado','tipo'=>'G'],
['codigo'=>'98300','nombre'=>'Pago de Dividendos','tipo'=>'G'],
['codigo'=>'99000','nombre'=>'Provisiones para Gastos Corrientes y de Capital','tipo'=>'G'],
['codigo'=>'99100','nombre'=>'Provisiones para Gastos de Capital','tipo'=>'G'],
['codigo'=>'99200','nombre'=>'Provisiones para Gastos Corrientes','tipo'=>'G'],



        ];



        foreach ($institucion as $claInst) {
			$item = (object) $claInst;
			$inst = [
				"codigo" => $item->codigo,
				"nombre" => $item->nombre,
				"tipo" => $item->tipo,
			];
			ClaPresupuestario::create($inst);
        }

    }
}
