<?php
namespace Database\Seeders;

use App\Models\BackEnd\intervenciones\ClaSectorial;

use Illuminate\Database\Seeder;

class ClaSectorialSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //

        $sector = [
            ['sector'=>'1','subsector'=>'0','tipo'=>'0','denominacion'=>'AGROPECUARIO','sigla'=>'AGROP'],
            ['sector'=>'1','subsector'=>'1','tipo'=>'0','denominacion'=>'AGRICOLA','sigla'=>'AGRIC'],
            ['sector'=>'1','subsector'=>'1','tipo'=>'1','denominacion'=>'INVESTIGACION AGRICOLA','sigla'=>'AGR01'],
            ['sector'=>'1','subsector'=>'1','tipo'=>'2','denominacion'=>'SANIDAD VEGETAL','sigla'=>'AGR02'],
            ['sector'=>'1','subsector'=>'1','tipo'=>'3','denominacion'=>'INFRAESTRUCTURA DE APOYO AGRICOLA','sigla'=>'AGR03'],
            ['sector'=>'1','subsector'=>'1','tipo'=>'4','denominacion'=>'EXTENSION Y CAPACITACION','sigla'=>'AGR04'],
            ['sector'=>'1','subsector'=>'1','tipo'=>'5','denominacion'=>'EQUIPAMIENTO APOYO AGRICOLA','sigla'=>'AGR05'],
            ['sector'=>'1','subsector'=>'1','tipo'=>'6','denominacion'=>'FOMENTO A LA PRODUCCION AGRICOLA','sigla'=>'AGR06'],
            ['sector'=>'1','subsector'=>'2','tipo'=>'0','denominacion'=>'PECUARIA','sigla'=>'PECUA'],
            ['sector'=>'1','subsector'=>'2','tipo'=>'1','denominacion'=>'INVESTIGACION PECUARIA','sigla'=>'PEC01'],
            ['sector'=>'1','subsector'=>'2','tipo'=>'2','denominacion'=>'EXTENSION Y CAPACITACION PECUARIA','sigla'=>'PEC02'],
            ['sector'=>'1','subsector'=>'2','tipo'=>'3','denominacion'=>'FOMENTO GANADERO','sigla'=>'PEC03'],
            ['sector'=>'1','subsector'=>'2','tipo'=>'4','denominacion'=>'SANIDAD ANIMAL','sigla'=>'PEC04'],
            ['sector'=>'1','subsector'=>'2','tipo'=>'5','denominacion'=>'INFRAESTRUCTURA DE APOYO PECUARIO','sigla'=>'PEC05'],
            ['sector'=>'1','subsector'=>'2','tipo'=>'6','denominacion'=>'MEJORAMIENTO GENÉTICO','sigla'=>'PEC06'],
            ['sector'=>'1','subsector'=>'2','tipo'=>'7','denominacion'=>'PRADERAS, FORRAJES Y NUTRICIÓN ANIMAL','sigla'=>'PEC07'],
            ['sector'=>'1','subsector'=>'2','tipo'=>'8','denominacion'=>'DESARROLLO APICOLA','sigla'=>'PEC08'],
            ['sector'=>'1','subsector'=>'2','tipo'=>'9','denominacion'=>'DESARROLLO AVICOLA','sigla'=>'PEC09'],
            ['sector'=>'1','subsector'=>'2','tipo'=>'10','denominacion'=>'EQUIPAMIENTO PARA APOYO PECUARIO','sigla'=>'PEC10'],
            ['sector'=>'1','subsector'=>'3','tipo'=>'0','denominacion'=>'DESARROLLO PESQUERO Y ACUICOLA','sigla'=>'SILVI'],
            ['sector'=>'1','subsector'=>'3','tipo'=>'1','denominacion'=>'PESCA EN CAUSES NATURALES','sigla'=>'SIL01'],
            ['sector'=>'1','subsector'=>'3','tipo'=>'2','denominacion'=>'AGROSILVOPASTORIL','sigla'=>'SIL02'],
            ['sector'=>'1','subsector'=>'3','tipo'=>'3','denominacion'=>'ACUICULTURA (CRIANZA ARTIFICIAL)','sigla'=>'SIL03'],
            ['sector'=>'1','subsector'=>'3','tipo'=>'4','denominacion'=>'INFRAESTRUCTURA DE APOYO EN ACUICULTURA','sigla'=>'SIL04'],
            ['sector'=>'1','subsector'=>'3','tipo'=>'5','denominacion'=>'INVESTIGACIÓN DESARROLLO PESQUERO','sigla'=>'INVDP'],
            ['sector'=>'1','subsector'=>'4','tipo'=>'0','denominacion'=>'SEGURIDAD Y SOBERANIA ALIMENTARIA','sigla'=>'SEGAL'],
            ['sector'=>'1','subsector'=>'4','tipo'=>'1','denominacion'=>'SEGURIDAD Y SOBERANIA ALIMENTARIA AGRICOLA','sigla'=>'SEG01'],
            ['sector'=>'1','subsector'=>'4','tipo'=>'2','denominacion'=>'SEGURIDAD Y SOBERANIA ALIMENTARIA PECUARIA','sigla'=>'SEG02'],
            ['sector'=>'1','subsector'=>'4','tipo'=>'3','denominacion'=>'INVESTIGACION SEGURIDAD Y SOBERANIA ALIMENTARIA','sigla'=>'INVSSA'],
            ['sector'=>'1','subsector'=>'5','tipo'=>'0','denominacion'=>'RIEGO','sigla'=>'RIE'],
            ['sector'=>'1','subsector'=>'5','tipo'=>'1','denominacion'=>'CONSTRUCCIÓN DE SISTEMAS DE RIEGO','sigla'=>'RIE01'],
            ['sector'=>'1','subsector'=>'5','tipo'=>'2','denominacion'=>'MEJORAMIENTO Y AMPLIACIÓN DE SISTEMA DE RIEGO','sigla'=>'RIE02'],
            ['sector'=>'1','subsector'=>'5','tipo'=>'3','denominacion'=>'REHABILITACIÓN DE SISTEMAS DE RIEGO','sigla'=>'RIE03'],
            ['sector'=>'1','subsector'=>'5','tipo'=>'4','denominacion'=>'OTROS','sigla'=>'RIE04'],
            ['sector'=>'1','subsector'=>'5','tipo'=>'5','denominacion'=>'MICRORIEGO Y OTROS (ATAJADOS, RESERVORIOS Y PERFORACIÓN DEPOZOS)','sigla'=>'RIE05'],
            ['sector'=>'1','subsector'=>'5','tipo'=>'6','denominacion'=>'DRENAJES','sigla'=>'RIE06'],
            ['sector'=>'1','subsector'=>'5','tipo'=>'7','denominacion'=>'OTROS RIEGO','sigla'=>'OTRIE'],
            ['sector'=>'1','subsector'=>'5','tipo'=>'8','denominacion'=>'INVESTIGACIÓN RIEGO','sigla'=>'RIE08'],
            ['sector'=>'1','subsector'=>'6','tipo'=>'0','denominacion'=>'MULTIPROGRAMA AGROPECUARIO','sigla'=>'MAGRP'],
            ['sector'=>'1','subsector'=>'6','tipo'=>'1','denominacion'=>'MULTIPROGRAMA','sigla'=>'MULT01'],
            ['sector'=>'1','subsector'=>'7','tipo'=>'0','denominacion'=>'OTROS AGROPECUARIO','sigla'=>'OAGR'],
            ['sector'=>'1','subsector'=>'7','tipo'=>'1','denominacion'=>'SANEAMIENTO TITULACIÓN Y DISTRIBUCIÓN DE TIERRAS','sigla'=>'OTR01'],
            ['sector'=>'1','subsector'=>'7','tipo'=>'2','denominacion'=>'OTROS','sigla'=>'OTR02'],
            ['sector'=>'2','subsector'=>'0','tipo'=>'0','denominacion'=>'MINERO','sigla'=>'MINER'],
            ['sector'=>'2','subsector'=>'1','tipo'=>'0','denominacion'=>'DESARROLLO MINERO','sigla'=>'MIN'],
            ['sector'=>'2','subsector'=>'1','tipo'=>'1','denominacion'=>'PROSPECCION Y EXPLORACION MINERA','sigla'=>'MIN01'],
            ['sector'=>'2','subsector'=>'1','tipo'=>'2','denominacion'=>'EXPLOTACIÓN Y PRODUCCIÓN DE MINERALES','sigla'=>'MIN02'],
            ['sector'=>'2','subsector'=>'1','tipo'=>'3','denominacion'=>'COMERCIALIZACIÓN DE MINERALES','sigla'=>'MIN03'],
            ['sector'=>'2','subsector'=>'1','tipo'=>'4','denominacion'=>'INDUSTRIALIZACIÓN MINERA','sigla'=>'MIN04'],
            ['sector'=>'2','subsector'=>'1','tipo'=>'5','denominacion'=>'INVESTIGACIÓN MINERA','sigla'=>'MIN05'],
            ['sector'=>'2','subsector'=>'1','tipo'=>'6','denominacion'=>'TRATAMIENTO DE RESIDUOS MINEROS','sigla'=>'MIN06'],
            ['sector'=>'2','subsector'=>'1','tipo'=>'7','denominacion'=>'REMEDIACIÓN DE PASIVOS AMBIENTALES','sigla'=>'MIN07'],
            ['sector'=>'2','subsector'=>'1','tipo'=>'8','denominacion'=>'OTROS MINERIA','sigla'=>'OTRMIN'],
            ['sector'=>'2','subsector'=>'1','tipo'=>'9','denominacion'=>'CONCENTRACION, FUNDICION Y REFINACION DE MINERALES','sigla'=>'MIN09'],
            ['sector'=>'2','subsector'=>'1','tipo'=>'10','denominacion'=>'ASISTENCIA Y CAPACITACION EN MINERIA','sigla'=>'MIN10'],
            ['sector'=>'2','subsector'=>'1','tipo'=>'11','denominacion'=>'INVESTIGACIÓN MINERA','sigla'=>'MIN11'],
            ['sector'=>'3','subsector'=>'0','tipo'=>'0','denominacion'=>'INDUSTRIA','sigla'=>'INDUS'],
            ['sector'=>'3','subsector'=>'1','tipo'=>'0','denominacion'=>'AGROINDUSTRIA','sigla'=>'AGROI'],
            ['sector'=>'3','subsector'=>'1','tipo'=>'1','denominacion'=>'TRANSFORMACIÓN DE ALIMENTOS Y BEBIDAS','sigla'=>'AGRO01'],
            ['sector'=>'3','subsector'=>'1','tipo'=>'2','denominacion'=>'COMERCIALIZACIÓN DE ALIMENTOS Y BEBIDAS','sigla'=>'AGRO02'],
            ['sector'=>'3','subsector'=>'1','tipo'=>'3','denominacion'=>'FOMENTO A LA PRODUCCION AGROINDUSTRIAL','sigla'=>'AGRO03'],
            ['sector'=>'3','subsector'=>'2','tipo'=>'0','denominacion'=>'INDUSTRIA MANUFACTURERA','sigla'=>'INMAN'],
            ['sector'=>'3','subsector'=>'2','tipo'=>'1','denominacion'=>'TRANSFORMACIÓN DE TEXTILES Y PRENDAS DE VESTIR','sigla'=>'INMA01'],
            ['sector'=>'3','subsector'=>'2','tipo'=>'2','denominacion'=>'TRANSFORMACIÓN DE MUEBLES','sigla'=>'INMA02'],
            ['sector'=>'3','subsector'=>'2','tipo'=>'3','denominacion'=>'TRANSFORMACIÓN DE CUEROS Y CALZADOS','sigla'=>'INMA03'],
            ['sector'=>'3','subsector'=>'2','tipo'=>'4','denominacion'=>'TRANSFORMACIÓN DE PRODUCTOS ELABORADOS DE METAL','sigla'=>'INMA04'],
            ['sector'=>'3','subsector'=>'2','tipo'=>'5','denominacion'=>'COMERCIALIZACIÓN DE MANUFACTURAS','sigla'=>'INMA05'],
            ['sector'=>'3','subsector'=>'2','tipo'=>'6','denominacion'=>'FOMENTO DE PROMOCIÓN DE LA PRODUCCION MANUFACTURERA Y MICROEMPRESA','sigla'=>'INMA06'],
            ['sector'=>'3','subsector'=>'2','tipo'=>'7','denominacion'=>'OTRAS MANUFACTURAS','sigla'=>'INMA07'],
            ['sector'=>'3','subsector'=>'3','tipo'=>'0','denominacion'=>'MULTIPROGRAMA INDUSTRIA','sigla'=>'MGRP'],
            ['sector'=>'3','subsector'=>'3','tipo'=>'1','denominacion'=>'MULTIPROGRAMA','sigla'=>'MULT02'],
            ['sector'=>'3','subsector'=>'4','tipo'=>'0','denominacion'=>'OTROS INDUSTRIA','sigla'=>'OTRIND'],
            ['sector'=>'3','subsector'=>'4','tipo'=>'1','denominacion'=>'OTROS','sigla'=>'OTR03'],
            ['sector'=>'3','subsector'=>'4','tipo'=>'2','denominacion'=>'OTROS ARTESANIAS','sigla'=>'OTRAR'],
            ['sector'=>'3','subsector'=>'5','tipo'=>'0','denominacion'=>'INVESTIGACION INDUSTRIA','sigla'=>'INVIND'],
            ['sector'=>'3','subsector'=>'5','tipo'=>'1','denominacion'=>'INVESTIGACION INDUSTRIA','sigla'=>'INVIND01'],
            ['sector'=>'4','subsector'=>'0','tipo'=>'0','denominacion'=>'HIDROCARBUROS','sigla'=>'HIDRO'],
            ['sector'=>'4','subsector'=>'1','tipo'=>'0','denominacion'=>'HIDROCARBUROS','sigla'=>'HID'],
            ['sector'=>'4','subsector'=>'1','tipo'=>'1','denominacion'=>'PROSPECCION Y EXPLORACION DE HIDROCARBUROS','sigla'=>'HID01'],
            ['sector'=>'4','subsector'=>'1','tipo'=>'2','denominacion'=>'EXPLOTACION O PRODUCCION DE HIDROCARBUROS','sigla'=>'HID02'],
            ['sector'=>'4','subsector'=>'1','tipo'=>'3','denominacion'=>'TRANSPORTE DE HIDROCARBUROS','sigla'=>'HID03'],
            ['sector'=>'4','subsector'=>'1','tipo'=>'4','denominacion'=>'COMERCIALIZACION DE HIDROCARBUROS','sigla'=>'HID04'],
            ['sector'=>'4','subsector'=>'1','tipo'=>'5','denominacion'=>'INDUSTRIALIZACION DE HIDROCARBUROS','sigla'=>'HID05'],
            ['sector'=>'4','subsector'=>'1','tipo'=>'6','denominacion'=>'REDES DE DISTRIBUCIÓN DE GAS','sigla'=>'HID06'],
            ['sector'=>'4','subsector'=>'1','tipo'=>'7','denominacion'=>'REMEDIACIÓN AMBIENTAL','sigla'=>'HID07'],
            ['sector'=>'4','subsector'=>'1','tipo'=>'8','denominacion'=>'OTROS HIDROCARBUROS','sigla'=>'OTRHID'],
            ['sector'=>'5','subsector'=>'0','tipo'=>'0','denominacion'=>'ENERGIA','sigla'=>'ENERG'],
            ['sector'=>'5','subsector'=>'1','tipo'=>'0','denominacion'=>'ENERGIA ELECTRICA','sigla'=>'ENELC01'],
            ['sector'=>'5','subsector'=>'1','tipo'=>'1','denominacion'=>'GENERACION DE ENERGIA ELECTRICA','sigla'=>'ENELC02'],
            ['sector'=>'5','subsector'=>'1','tipo'=>'2','denominacion'=>'TRANSMISION DE ENERGIA ELECTRICA','sigla'=>'ENELC03'],
            ['sector'=>'5','subsector'=>'1','tipo'=>'3','denominacion'=>'DISTRIBUCIÓN DE ENERGÍA ELECTRICA','sigla'=>'ENELC04'],
            ['sector'=>'5','subsector'=>'1','tipo'=>'4','denominacion'=>'ELECTRIFICACION RURAL','sigla'=>'ENELC05'],
            ['sector'=>'5','subsector'=>'2','tipo'=>'0','denominacion'=>'ENERGIAS ALTERNATIVAS','sigla'=>'OTRENEL'],
            ['sector'=>'5','subsector'=>'2','tipo'=>'1','denominacion'=>'EOLICA','sigla'=>'ENELALT'],
            ['sector'=>'5','subsector'=>'2','tipo'=>'2','denominacion'=>'GEOTERMICA','sigla'=>'ENEEO'],
            ['sector'=>'5','subsector'=>'2','tipo'=>'3','denominacion'=>'FOTOVOLTAICA','sigla'=>'ENEGEO'],
            ['sector'=>'5','subsector'=>'2','tipo'=>'4','denominacion'=>'BIOMASA','sigla'=>'ENEBIO'],
            ['sector'=>'5','subsector'=>'2','tipo'=>'5','denominacion'=>'NUCLEAR','sigla'=>'ENENU'],
            ['sector'=>'5','subsector'=>'3','tipo'=>'0','denominacion'=>'OTROS ENERGÍA','sigla'=>'OTENE'],
            ['sector'=>'5','subsector'=>'3','tipo'=>'1','denominacion'=>'OTROS ENERGÍA','sigla'=>'OTR04'],
            ['sector'=>'5','subsector'=>'4','tipo'=>'0','denominacion'=>'MULTIPROGRAMA ENERGÍA','sigla'=>'MENER'],
            ['sector'=>'5','subsector'=>'4','tipo'=>'1','denominacion'=>'MULTIPROGRAMA','sigla'=>'MULT03'],
            ['sector'=>'5','subsector'=>'5','tipo'=>'0','denominacion'=>'INVESTIGACIÓN ENERGÍA','sigla'=>'INVDEN'],
            ['sector'=>'5','subsector'=>'5','tipo'=>'1','denominacion'=>'INVESTIGACIÓN EN DESARROLLO DE LA ENERGÍA','sigla'=>'INVDEN01'],
            ['sector'=>'6','subsector'=>'0','tipo'=>'0','denominacion'=>'TRANSPORTES','sigla'=>'TRANS'],
            ['sector'=>'6','subsector'=>'1','tipo'=>'0','denominacion'=>'CAMINERO','sigla'=>'CAM'],
            ['sector'=>'6','subsector'=>'1','tipo'=>'1','denominacion'=>'CONSTRUCCION CARRETERAS PAVIMENTADAS','sigla'=>'CAM01'],
            ['sector'=>'6','subsector'=>'1','tipo'=>'2','denominacion'=>'CONSTRUCCION CARRETERAS NO PAVIMENTADAS','sigla'=>'CAM02'],
            ['sector'=>'6','subsector'=>'1','tipo'=>'3','denominacion'=>'MEJORAMIENTO DE CARRETERAS','sigla'=>'CAM03'],
            ['sector'=>'6','subsector'=>'1','tipo'=>'4','denominacion'=>'MANTENIMIENTO DE CARRETERAS','sigla'=>'CAM04'],
            ['sector'=>'6','subsector'=>'1','tipo'=>'5','denominacion'=>'REHABILITACIÓN DE CARRETERAS','sigla'=>'CAM05'],
            ['sector'=>'6','subsector'=>'1','tipo'=>'6','denominacion'=>'APERTURA DE CAMINOS VECINALES','sigla'=>'CAM06'],
            ['sector'=>'6','subsector'=>'1','tipo'=>'7','denominacion'=>'MEJORAMIENTO DE CAMINOS VECINALES','sigla'=>'CAM07'],
            ['sector'=>'6','subsector'=>'1','tipo'=>'8','denominacion'=>'CONSTRUCCION DE PUENTES','sigla'=>'CAM08'],
            ['sector'=>'6','subsector'=>'1','tipo'=>'9','denominacion'=>'REHABILITACIÓN DE PUENTES','sigla'=>'CAM09'],
            ['sector'=>'6','subsector'=>'1','tipo'=>'10','denominacion'=>'SERVICIOS POR TRANSPORTE TERRESTRE','sigla'=>'CAM10'],
            ['sector'=>'6','subsector'=>'1','tipo'=>'11','denominacion'=>'CONTROL Y SEGURIDAD DEL TRAFICO TERRESTRE','sigla'=>'CAM11'],
            ['sector'=>'6','subsector'=>'1','tipo'=>'12','denominacion'=>'MANTENIMIENTO DE PUENTES','sigla'=>'CAM12'],
            ['sector'=>'6','subsector'=>'2','tipo'=>'0','denominacion'=>'FERROVIARIO','sigla'=>'FER'],
            ['sector'=>'6','subsector'=>'2','tipo'=>'1','denominacion'=>'CONSTRUCCIÓN DE INFRAESTRUCTURA FERROVIARIA','sigla'=>'FER01'],
            ['sector'=>'6','subsector'=>'2','tipo'=>'2','denominacion'=>'EQUIPAMIENTO DE TRACCION Y MATERIAL RODANTE','sigla'=>'FER02'],
            ['sector'=>'6','subsector'=>'2','tipo'=>'3','denominacion'=>'MEJORAMIENTO DE INFRAESTRUCTURA FERROVIARIA','sigla'=>'FER03'],
            ['sector'=>'6','subsector'=>'2','tipo'=>'4','denominacion'=>'REHABILITACION DE LINEAS FERREAS','sigla'=>'FER04'],
            ['sector'=>'6','subsector'=>'2','tipo'=>'5','denominacion'=>'SERVICIOS FERROVIARIOS','sigla'=>'FER05'],
            ['sector'=>'6','subsector'=>'2','tipo'=>'6','denominacion'=>'CONTROL Y SEGURIDAD DEL TRANSPORTE FERROVIARIO','sigla'=>'FER06'],
            ['sector'=>'6','subsector'=>'3','tipo'=>'0','denominacion'=>'AÉREO','sigla'=>'AER'],
            ['sector'=>'6','subsector'=>'3','tipo'=>'1','denominacion'=>'CONSTRUCCION DE INFRAESTRUCTURA AEROPORTUARIA','sigla'=>'AER01'],
            ['sector'=>'6','subsector'=>'3','tipo'=>'2','denominacion'=>'EQUIPAMIENTO PARA LA NAVEGACIÓN Y SERVICIOS AUXILIARES','sigla'=>'AER02'],
            ['sector'=>'6','subsector'=>'3','tipo'=>'3','denominacion'=>'MEJORAMIENTO DE INFRAESTRUCTURA AEROPORTUARIA','sigla'=>'AER03'],
            ['sector'=>'6','subsector'=>'3','tipo'=>'4','denominacion'=>'REHABILITACIÓN DE INFRAESTRUCTURA AEROPORTUARIA','sigla'=>'AER04'],
            ['sector'=>'6','subsector'=>'3','tipo'=>'5','denominacion'=>'MANTENIMIENTO DE INFRAESTRUCTURA AEROPORTUARIA','sigla'=>'AER05'],
            ['sector'=>'6','subsector'=>'3','tipo'=>'6','denominacion'=>'CONSTRUCCION DE PISTAS','sigla'=>'AER06'],
            ['sector'=>'6','subsector'=>'3','tipo'=>'7','denominacion'=>'CONSTRUCCION DE TERMINALES AEREAS','sigla'=>'AER07'],
            ['sector'=>'6','subsector'=>'3','tipo'=>'8','denominacion'=>'MEJORAMIENTO Y MANTENIMIENTO DE AERONAVES','sigla'=>'AER08'],
            ['sector'=>'6','subsector'=>'3','tipo'=>'9','denominacion'=>'SERVICIOS DE TRANSPORTE AÉREO','sigla'=>'AER09'],
            ['sector'=>'6','subsector'=>'3','tipo'=>'10','denominacion'=>'CONTROL Y SEGURIDAD DEL TRANSPORTE AEREO','sigla'=>'AER10'],
            ['sector'=>'6','subsector'=>'4','tipo'=>'0','denominacion'=>'TRANSPORTE FLUVIAL Y LACUSTRE','sigla'=>'HIDROV'],
            ['sector'=>'6','subsector'=>'4','tipo'=>'1','denominacion'=>'CONSTRUCCION Y EQUIPAMIENTO DE PUERTOS','sigla'=>'HIDR01'],
            ['sector'=>'6','subsector'=>'4','tipo'=>'2','denominacion'=>'MEJORAS PARA LA NAVEGACION','sigla'=>'HIDR02'],
            ['sector'=>'6','subsector'=>'4','tipo'=>'3','denominacion'=>'CONSTRUCCIÓN DE INFRAESTRUCTURA FLUVIAL Y LACUSTRE','sigla'=>'HIDR03'],
            ['sector'=>'6','subsector'=>'4','tipo'=>'4','denominacion'=>'EQUIPAMIENTO PARA LA NAVEGACIÓN Y SERVICIOS AUXILIARES','sigla'=>'HIDR04'],
            ['sector'=>'6','subsector'=>'4','tipo'=>'5','denominacion'=>'MEJORAMIENTO DE INFRAESTRUCTURA FLUVIAL Y LACUSTRE','sigla'=>'HIDR05'],
            ['sector'=>'6','subsector'=>'4','tipo'=>'6','denominacion'=>'REHABILITACIÓN DE INFRAESTRUCTURA FLUVIAL Y LACUSTRE','sigla'=>'HIDR06'],
            ['sector'=>'6','subsector'=>'4','tipo'=>'7','denominacion'=>'MANTENIMIENTO DE INFRAESTRUCTURA FLUVIAL Y LACUSTRE','sigla'=>'HIDR07'],
            ['sector'=>'6','subsector'=>'4','tipo'=>'8','denominacion'=>'SERVICIO DE TRANSPORTE FLUVIAL Y LACUSTRE','sigla'=>'HIDR08'],
            ['sector'=>'6','subsector'=>'4','tipo'=>'9','denominacion'=>'CONTROL Y SEGURIDAD DEL TRAFICO FLUVIAL Y LACUSTRE','sigla'=>'HIDR09'],
            ['sector'=>'6','subsector'=>'5','tipo'=>'0','denominacion'=>'MULTIPROGRAMA TRANSPORTES','sigla'=>'MTRNS'],
            ['sector'=>'6','subsector'=>'5','tipo'=>'1','denominacion'=>'MULTIPROGRAMA','sigla'=>'MULT04'],
            ['sector'=>'6','subsector'=>'6','tipo'=>'0','denominacion'=>'OTROS TRANSPORTES','sigla'=>'OTRTRS'],
            ['sector'=>'6','subsector'=>'6','tipo'=>'1','denominacion'=>'TRANSPORTE POR CABLE','sigla'=>'TRCAB'],
            ['sector'=>'6','subsector'=>'6','tipo'=>'2','denominacion'=>'OTROS TRANSPORTES','sigla'=>'OTR05'],
            ['sector'=>'6','subsector'=>'7','tipo'=>'0','denominacion'=>'INVESTIGACIÓN TRANSPORTES','sigla'=>'INVT'],
            ['sector'=>'6','subsector'=>'7','tipo'=>'1','denominacion'=>'INVESTIGACIÓN TRANSPORTES','sigla'=>'INVT01'],
            ['sector'=>'7','subsector'=>'0','tipo'=>'0','denominacion'=>'COMUNICACIONES','sigla'=>'COMUN'],
            ['sector'=>'7','subsector'=>'1','tipo'=>'0','denominacion'=>'TELECOMUNICACIONES','sigla'=>'TEL'],
            ['sector'=>'7','subsector'=>'1','tipo'=>'1','denominacion'=>'CONSTRUCCIONES E INFRAESTRUCTURA','sigla'=>'TEL01'],
            ['sector'=>'7','subsector'=>'1','tipo'=>'2','denominacion'=>'EQUIPAMIENTO DE TELECOMUNICACIONES','sigla'=>'TEL02'],
            ['sector'=>'7','subsector'=>'1','tipo'=>'3','denominacion'=>'MEJORAMIENTO DE INFRAESTRUCTURA DE TELECOMUNICACIONES','sigla'=>'TEL03'],
            ['sector'=>'7','subsector'=>'1','tipo'=>'4','denominacion'=>'REHABILITACIÓN DE INFRAESTRUCTURA DE TELECOMUNICACIONES','sigla'=>'TEL04'],
            ['sector'=>'7','subsector'=>'1','tipo'=>'5','denominacion'=>'SERVICIO DE TELECOMUNICACIONES','sigla'=>'TEL05'],
            ['sector'=>'7','subsector'=>'1','tipo'=>'6','denominacion'=>'GESTION DEL ESPACIO ELECTROMAGNETICO','sigla'=>'TEL06'],
            ['sector'=>'7','subsector'=>'2','tipo'=>'0','denominacion'=>'SERVICIO POSTAL','sigla'=>'POSTA'],
            ['sector'=>'7','subsector'=>'2','tipo'=>'1','denominacion'=>'CONSTRUCCIONES E INFRAESTRUCTURA DE CORREOS','sigla'=>'POS01'],
            ['sector'=>'7','subsector'=>'2','tipo'=>'2','denominacion'=>'EQUIPAMIENTO DE SERVICIO POSTAL','sigla'=>'POS02'],
            ['sector'=>'7','subsector'=>'2','tipo'=>'3','denominacion'=>'SERVICIO POSTAL','sigla'=>'POS03'],
            ['sector'=>'7','subsector'=>'3','tipo'=>'0','denominacion'=>'MULTIPROGRAMA COMUNICACIONES','sigla'=>'MCOM'],
            ['sector'=>'7','subsector'=>'3','tipo'=>'1','denominacion'=>'MULTIPROGRAMA','sigla'=>'MULT05'],
            ['sector'=>'7','subsector'=>'4','tipo'=>'0','denominacion'=>'OTROS COMUNICACIONES','sigla'=>'OTRCOM'],
            ['sector'=>'7','subsector'=>'4','tipo'=>'1','denominacion'=>'OTROS','sigla'=>'OTR06'],
            ['sector'=>'7','subsector'=>'5','tipo'=>'0','denominacion'=>'INVESTIGACIÓN COMUNICACIONES','sigla'=>'INVC'],
            ['sector'=>'7','subsector'=>'5','tipo'=>'1','denominacion'=>'INVESTIGACIÓN COMUNICACIONES','sigla'=>'INVC01'],
            ['sector'=>'8','subsector'=>'0','tipo'=>'0','denominacion'=>'SALUD','sigla'=>'SALUD'],
            ['sector'=>'8','subsector'=>'1','tipo'=>'0','denominacion'=>'INFRAESTRUCTURA DE SALUD','sigla'=>'SAL'],
            ['sector'=>'8','subsector'=>'1','tipo'=>'1','denominacion'=>'CONSTRUCCION DE INFRAESTRUCTURA Y EQUIPAMIENTO DE HOSPITALES','sigla'=>'SAL01'],
            ['sector'=>'8','subsector'=>'1','tipo'=>'2','denominacion'=>'CONSTRUCCION DE INFRAESTRUCTURA Y EQUIPAMIENTO DE CENTROS DE SALUD','sigla'=>'SAL02'],
            ['sector'=>'8','subsector'=>'1','tipo'=>'3','denominacion'=>'MEJORAMIENTO DE INFRAESTRUCTURA DE HOSPITALES','sigla'=>'SAL03'],
            ['sector'=>'8','subsector'=>'1','tipo'=>'4','denominacion'=>'MEJORAMIENTO DE INFRAESTRUCTURA DE CENTROS DE SALUD','sigla'=>'SAL04'],
            ['sector'=>'8','subsector'=>'1','tipo'=>'5','denominacion'=>'OTROS INFRAESTRUCTURA DE SALUD','sigla'=>'SAL05'],
            ['sector'=>'8','subsector'=>'2','tipo'=>'0','denominacion'=>'PLANIFICACIÓN Y PREVENCIÓN DE SALUD','sigla'=>'PLA'],
            ['sector'=>'8','subsector'=>'2','tipo'=>'1','denominacion'=>'PLANIFICACION Y EDUCACIÓN PARA LA SALUD','sigla'=>'PLA01'],
            ['sector'=>'8','subsector'=>'2','tipo'=>'2','denominacion'=>'PROGRAMAS EN PREVENCIÓN Y EDUCACION PARA LA SALUD','sigla'=>'PLA02'],
            ['sector'=>'8','subsector'=>'2','tipo'=>'3','denominacion'=>'REGULACIÓN Y CONTROL SANITARIO','sigla'=>'PLA03'],
            ['sector'=>'8','subsector'=>'2','tipo'=>'4','denominacion'=>'PROMOCION DE LA SALUD','sigla'=>'PLA04'],
            ['sector'=>'8','subsector'=>'3','tipo'=>'0','denominacion'=>'ATENCIÓN EN SALUD','sigla'=>'ASAL'],
            ['sector'=>'8','subsector'=>'3','tipo'=>'1','denominacion'=>'ATENCIÓN PRIMARIA EN SALUD','sigla'=>'ASA01'],
            ['sector'=>'8','subsector'=>'3','tipo'=>'2','denominacion'=>'PROGRAMAS INTEGRALES DE SALUD','sigla'=>'ASA02'],
            ['sector'=>'8','subsector'=>'3','tipo'=>'3','denominacion'=>'EPIDEMIOLOGIA','sigla'=>'ASA03'],
            ['sector'=>'8','subsector'=>'3','tipo'=>'4','denominacion'=>'DESARROLLO MEDICINA TRADICIONAL','sigla'=>'ASA04'],
            ['sector'=>'8','subsector'=>'3','tipo'=>'5','denominacion'=>'SALUD OCUPACIONAL','sigla'=>'ASA05'],
            ['sector'=>'8','subsector'=>'4','tipo'=>'0','denominacion'=>'MULTIPROGRAMA SALUD','sigla'=>'MULSAL'],
            ['sector'=>'8','subsector'=>'4','tipo'=>'1','denominacion'=>'MULTIPROGRAMA','sigla'=>'MULT06'],
            ['sector'=>'8','subsector'=>'5','tipo'=>'0','denominacion'=>'OTROS SALUD','sigla'=>'OTSLD'],
            ['sector'=>'8','subsector'=>'5','tipo'=>'1','denominacion'=>'OTROS','sigla'=>'OTR07'],
            ['sector'=>'8','subsector'=>'6','tipo'=>'0','denominacion'=>'TELESALUD','sigla'=>'TELES'],
            ['sector'=>'8','subsector'=>'6','tipo'=>'1','denominacion'=>'TELESALUD','sigla'=>'TELES01'],
            ['sector'=>'8','subsector'=>'7','tipo'=>'0','denominacion'=>'INVESTIGACION SALUD','sigla'=>'INVS'],
            ['sector'=>'8','subsector'=>'7','tipo'=>'1','denominacion'=>'INVESTIGACION SALUD','sigla'=>'INVS01'],
            ['sector'=>'9','subsector'=>'0','tipo'=>'0','denominacion'=>'EDUCACIÓN','sigla'=>'EDUCA'],
            ['sector'=>'9','subsector'=>'1','tipo'=>'0','denominacion'=>'INFRAESTRUCTURA DE EDUCACIÓN','sigla'=>'IED'],
            ['sector'=>'9','subsector'=>'1','tipo'=>'1','denominacion'=>'CONSTRUCCIÓN Y EQUIPAMIENTO DE ESCUELAS Y COLEGIOS','sigla'=>'IED01'],
            ['sector'=>'9','subsector'=>'1','tipo'=>'2','denominacion'=>'CONSTRUCCIÓN Y EQUIPAMIENTO DE CENTROS DE EDUCACION NO FORMAL','sigla'=>'IED02'],
            ['sector'=>'9','subsector'=>'1','tipo'=>'3','denominacion'=>'INFRAESTRUCTURA DE EDUCACIÓN SUPERIOR','sigla'=>'IED03'],
            ['sector'=>'9','subsector'=>'1','tipo'=>'4','denominacion'=>'OTRA INFRAESTRUCTURA EDUCATIVA','sigla'=>'IED04'],
            ['sector'=>'9','subsector'=>'1','tipo'=>'5','denominacion'=>'CONSTRUCCIÓN Y EQUIPAMIENTO EN EDUCACIÓN ALTERNATIVA','sigla'=>'IED05'],
            ['sector'=>'9','subsector'=>'1','tipo'=>'6','denominacion'=>'CONSTRUCCIÓN Y EQUIPAMIENTO EN EDUCACIÓN ESPECIAL','sigla'=>'IED06'],
            ['sector'=>'9','subsector'=>'2','tipo'=>'0','denominacion'=>'EDUCACIÓN FORMAL','sigla'=>'EDF'],
            ['sector'=>'9','subsector'=>'2','tipo'=>'1','denominacion'=>'EDUCACIÓN BASICA','sigla'=>'EDF01'],
            ['sector'=>'9','subsector'=>'2','tipo'=>'2','denominacion'=>'EDUCACIÓN SUPERIOR','sigla'=>'EDF02'],
            ['sector'=>'9','subsector'=>'2','tipo'=>'3','denominacion'=>'FORMACIÓN DOCENTE','sigla'=>'EDF03'],
            ['sector'=>'9','subsector'=>'2','tipo'=>'4','denominacion'=>'FORMACIÓN OCUPACIONAL','sigla'=>'EDF04'],
            ['sector'=>'9','subsector'=>'2','tipo'=>'5','denominacion'=>'ASISTENCIA EDUCATIVA','sigla'=>'EDF05'],
            ['sector'=>'9','subsector'=>'2','tipo'=>'6','denominacion'=>'DESARROLLO CURRICULAR EDUCACIÓN REGULAR','sigla'=>'EDF06'],
            ['sector'=>'9','subsector'=>'3','tipo'=>'0','denominacion'=>'EDUCACIÓN NO FORMAL','sigla'=>'EDN'],
            ['sector'=>'9','subsector'=>'3','tipo'=>'1','denominacion'=>'ALFABETIZACIÓN','sigla'=>'EDN01'],
            ['sector'=>'9','subsector'=>'3','tipo'=>'2','denominacion'=>'EDUCACIÓN POPULAR','sigla'=>'EDN02'],
            ['sector'=>'9','subsector'=>'3','tipo'=>'3','denominacion'=>'FORMACIÓN DE MANO DE OBRA','sigla'=>'EDN03'],
            ['sector'=>'9','subsector'=>'3','tipo'=>'4','denominacion'=>'DESARROLLO CURRICULAR EDUCACIÓN NO REGULAR','sigla'=>'EDN04'],
            ['sector'=>'9','subsector'=>'3','tipo'=>'5','denominacion'=>'POST ALFABETIZACIÓN','sigla'=>'EDN05'],
            ['sector'=>'9','subsector'=>'4','tipo'=>'0','denominacion'=>'MULTIPROGRAMA EDUCACION','sigla'=>'MEDUC'],
            ['sector'=>'9','subsector'=>'4','tipo'=>'1','denominacion'=>'MULTIPROGRAMA','sigla'=>'MULT07'],
            ['sector'=>'9','subsector'=>'4','tipo'=>'2','denominacion'=>'INVESTIGACIÓN EDUCACIÓN','sigla'=>'INVED09'],
            ['sector'=>'9','subsector'=>'5','tipo'=>'0','denominacion'=>'OTROS EDUCACION','sigla'=>'OTREDU'],
            ['sector'=>'9','subsector'=>'5','tipo'=>'1','denominacion'=>'OTROS','sigla'=>'OTR08'],
            ['sector'=>'9','subsector'=>'5','tipo'=>'2','denominacion'=>'PROMOCIÓN DE LA EDUCACIÓN INTEGRAL','sigla'=>'PROMED02'],
            ['sector'=>'9','subsector'=>'5','tipo'=>'3','denominacion'=>'INVESTIGACIÓN E INNOVACIÓN EDUCATIVA','sigla'=>'INVEIN03'],
            ['sector'=>'9','subsector'=>'5','tipo'=>'4','denominacion'=>'TECNOLOGÍAS DE INFORMACIÓN Y COMUNICACIÓN EN EDUCACIÓN','sigla'=>'TECICE04'],
            ['sector'=>'10','subsector'=>'0','tipo'=>'0','denominacion'=>'SANEAMIENTO BÁSICO','sigla'=>'SANEA'],
            ['sector'=>'10','subsector'=>'1','tipo'=>'0','denominacion'=>'AGUA POTABLE','sigla'=>'AGU'],
            ['sector'=>'10','subsector'=>'1','tipo'=>'1','denominacion'=>'AGUA POTABLE EN CAPITALES DE DEPARTAMENTO','sigla'=>'AGU01'],
            ['sector'=>'10','subsector'=>'1','tipo'=>'2','denominacion'=>'AGUA POTABLE EN CIUDADES INTERMEDIAS','sigla'=>'AGU02'],
            ['sector'=>'10','subsector'=>'1','tipo'=>'3','denominacion'=>'AGUA POTABLE EN POBLADOS RURALES','sigla'=>'AGU03'],
            ['sector'=>'10','subsector'=>'1','tipo'=>'4','denominacion'=>'PERFORACIÓN DE POZOS PARA AGUA POTABLE','sigla'=>'AGU04'],
            ['sector'=>'10','subsector'=>'1','tipo'=>'5','denominacion'=>'REHABILITACIÓN Y AMPLIACIÓN DE SISTEMAS DE AGUA','sigla'=>'AGU05'],
            ['sector'=>'10','subsector'=>'2','tipo'=>'0','denominacion'=>'ALCANTARILLADO','sigla'=>'ALC'],
            ['sector'=>'10','subsector'=>'2','tipo'=>'1','denominacion'=>'ALCANTARILLADO EN CAPITALES DE DEPARTAMENTO','sigla'=>'ALC01'],
            ['sector'=>'10','subsector'=>'2','tipo'=>'2','denominacion'=>'ALCANTARILLADO EN CIUDADES INTERMEDIAS','sigla'=>'ALC02'],
            ['sector'=>'10','subsector'=>'2','tipo'=>'3','denominacion'=>'ALCANTARILLADO EN POBLADOS RURALES','sigla'=>'ALC03'],
            ['sector'=>'10','subsector'=>'2','tipo'=>'4','denominacion'=>'LETRINIZACIÓN','sigla'=>'ALC04'],
            ['sector'=>'10','subsector'=>'2','tipo'=>'5','denominacion'=>'ALCANTARILLADO PLUVIAL EN CAPITALES DE DEPARTAMENTO','sigla'=>'ALC05'],
            ['sector'=>'10','subsector'=>'2','tipo'=>'6','denominacion'=>'ALCANTARILLADO PLUVIAL EN CIUDADES INTERMEDIAS','sigla'=>'ALC06'],
            ['sector'=>'10','subsector'=>'2','tipo'=>'7','denominacion'=>'ALCANTARILLADO PLUVIAL EN POBLADOS RURALES','sigla'=>'ALC07'],
            ['sector'=>'10','subsector'=>'3','tipo'=>'0','denominacion'=>'TRATAMIENTO','sigla'=>'TRS'],
            ['sector'=>'10','subsector'=>'3','tipo'=>'1','denominacion'=>'TRATAMIENTO DE AGUA POTABLE','sigla'=>'TRS01'],
            ['sector'=>'10','subsector'=>'3','tipo'=>'2','denominacion'=>'TRATAMIENTO DE AGUAS SERVIDAS','sigla'=>'TRS02'],
            ['sector'=>'10','subsector'=>'3','tipo'=>'3','denominacion'=>'TRATAMIENTO DE RESIDUOS SOLIDOS','sigla'=>'TRS03'],
            ['sector'=>'10','subsector'=>'3','tipo'=>'4','denominacion'=>'RECOLECCION Y ELIMINACION DE DESECHOS SOLIDOS','sigla'=>'TRS04'],
            ['sector'=>'10','subsector'=>'3','tipo'=>'5','denominacion'=>'REHABILITACIÓN DE PLANTAS DE TRATAMIENTO','sigla'=>'TRS05'],
            ['sector'=>'10','subsector'=>'4','tipo'=>'0','denominacion'=>'MULTIPROGRAMA SANEAMIENTO BASICO','sigla'=>'MSANB'],
            ['sector'=>'10','subsector'=>'4','tipo'=>'1','denominacion'=>'MULTIPROGRAMA','sigla'=>'MULT08'],
            ['sector'=>'10','subsector'=>'4','tipo'=>'2','denominacion'=>'AGUA POTABLE Y ALCANTARILLADO EN CAPITALES DE DEPARTAMENTO','sigla'=>'AG-01'],
            ['sector'=>'10','subsector'=>'4','tipo'=>'3','denominacion'=>'AGUA POTABLE Y ALCANTARILLADO EN CIUDADES INTERMEDIAS','sigla'=>'AG-02'],
            ['sector'=>'10','subsector'=>'4','tipo'=>'4','denominacion'=>'AGUA POTABLE Y ALCANTARILLADO EN POBLADOS RURALES','sigla'=>'AG-03'],
            ['sector'=>'10','subsector'=>'4','tipo'=>'5','denominacion'=>'AGUA Y LETRINIZACIÓN','sigla'=>'AG-04'],
            ['sector'=>'10','subsector'=>'4','tipo'=>'6','denominacion'=>'INVESTIGACIÓN SANEAMIENTO BÁSICO','sigla'=>'AG-05'],
            ['sector'=>'10','subsector'=>'5','tipo'=>'0','denominacion'=>'OTROS SANEAMIENTO BASICO','sigla'=>'OTRSB'],
            ['sector'=>'10','subsector'=>'5','tipo'=>'1','denominacion'=>'OTROS','sigla'=>'OTR09'],
            ['sector'=>'11','subsector'=>'0','tipo'=>'0','denominacion'=>'URBANISMO Y VIVIENDA','sigla'=>'URBVIV'],
            ['sector'=>'11','subsector'=>'1','tipo'=>'0','denominacion'=>'URBANISMO','sigla'=>'URB'],
            ['sector'=>'11','subsector'=>'1','tipo'=>'1','denominacion'=>'PLANIFICACION URBANA Y URBANIZACION','sigla'=>'URB01'],
            ['sector'=>'11','subsector'=>'1','tipo'=>'2','denominacion'=>'EQUIPAMIENTO E INFRAESTRUCTURA URBANA','sigla'=>'URB02'],
            ['sector'=>'11','subsector'=>'1','tipo'=>'3','denominacion'=>'EQUIPAMIENTO E INFRAESTRUCTURA RECREACIONAL','sigla'=>'URB03'],
            ['sector'=>'11','subsector'=>'1','tipo'=>'4','denominacion'=>'MEJORAMIENTO DE INFRAESTRUCTURA URBANA','sigla'=>'URB04'],
            ['sector'=>'11','subsector'=>'1','tipo'=>'5','denominacion'=>'VIAS URBANAS Y RURALES','sigla'=>'URB05'],
            ['sector'=>'11','subsector'=>'2','tipo'=>'0','denominacion'=>'VIVIENDA','sigla'=>'VIV'],
            ['sector'=>'11','subsector'=>'2','tipo'=>'1','denominacion'=>'PLANIFICACION PARA LA DOTACION DE LA VIVIENDA','sigla'=>'VIV01'],
            ['sector'=>'11','subsector'=>'2','tipo'=>'2','denominacion'=>'CONSTRUCCIÓN DE VIVIENDAS EN CAPITAL DE DEPARTAMENTO','sigla'=>'VIV02'],
            ['sector'=>'11','subsector'=>'2','tipo'=>'3','denominacion'=>'CONSTRUCCIÓN DE VIVIENDAS EN CIUDADES INTERMEDIAS','sigla'=>'VIV03'],
            ['sector'=>'11','subsector'=>'2','tipo'=>'4','denominacion'=>'CONSTRUCCIÓN DE VIVIENDAS EN POBLADOS RURALES','sigla'=>'VIV04'],
            ['sector'=>'11','subsector'=>'3','tipo'=>'0','denominacion'=>'MULTIPROGRAMA URBANISMO Y VIVIENDA','sigla'=>'MURVI'],
            ['sector'=>'11','subsector'=>'3','tipo'=>'1','denominacion'=>'MULTIPROGRAMA','sigla'=>'MULT09'],
            ['sector'=>'11','subsector'=>'3','tipo'=>'2','denominacion'=>'INVESTIGACIÓN URBANISMO Y VIVIENDA','sigla'=>'INVURBV'],
            ['sector'=>'11','subsector'=>'4','tipo'=>'0','denominacion'=>'OTROS URBANISMO Y VIVIENDA','sigla'=>'OTURV'],
            ['sector'=>'11','subsector'=>'4','tipo'=>'1','denominacion'=>'OTROS','sigla'=>'OTR10'],
            ['sector'=>'12','subsector'=>'0','tipo'=>'0','denominacion'=>'RECURSOS HÍDRICOS','sigla'=>'RECH'],
            ['sector'=>'12','subsector'=>'1','tipo'=>'0','denominacion'=>'APROVECHAMIENTO DE RECURSOS HIDRICOS','sigla'=>'APR'],
            ['sector'=>'12','subsector'=>'1','tipo'=>'1','denominacion'=>'CONSTRUCCION DE ATAJADOS Y RESERVORIOS','sigla'=>'APR01'],
            ['sector'=>'12','subsector'=>'1','tipo'=>'2','denominacion'=>'PERFORACION DE POZOS','sigla'=>'APR02'],
            ['sector'=>'12','subsector'=>'1','tipo'=>'3','denominacion'=>'EXPLORACION DE RECURSOS HÍDRICOS','sigla'=>'APR03'],
            ['sector'=>'12','subsector'=>'2','tipo'=>'0','denominacion'=>'MANEJO INTEGRAL DE CUENCAS','sigla'=>'MIC'],
            ['sector'=>'12','subsector'=>'2','tipo'=>'1','denominacion'=>'DEFENSIVOS Y DEFLECTORES FLUVIALES','sigla'=>'MIC01'],
            ['sector'=>'12','subsector'=>'2','tipo'=>'2','denominacion'=>'CONTROL DE AGUA Y EROSION','sigla'=>'MIC02'],
            ['sector'=>'12','subsector'=>'2','tipo'=>'3','denominacion'=>'CONTROL DE CARCAVAS Y AVENIDAS','sigla'=>'MIC03'],
            ['sector'=>'12','subsector'=>'2','tipo'=>'4','denominacion'=>'CANALIZACION DE RIOS','sigla'=>'MIC04'],
            ['sector'=>'12','subsector'=>'2','tipo'=>'5','denominacion'=>'GESTIÓN Y MANEJO DE CUENCAS','sigla'=>'MIC05'],
            ['sector'=>'12','subsector'=>'2','tipo'=>'6','denominacion'=>'REMEDIACIÓN DE PASIVOS AMBIENTALES','sigla'=>'MIC06'],
            ['sector'=>'12','subsector'=>'3','tipo'=>'0','denominacion'=>'MULTIPROGRAMA RECURSOS HIDRICOS','sigla'=>'MHIDR'],
            ['sector'=>'12','subsector'=>'3','tipo'=>'1','denominacion'=>'MULTIPROGRAMA','sigla'=>'MULT10'],
            ['sector'=>'12','subsector'=>'3','tipo'=>'2','denominacion'=>'INVESTIGACIÓN RECURSOS HÍDRICOS','sigla'=>'INVRH'],
            ['sector'=>'12','subsector'=>'4','tipo'=>'0','denominacion'=>'OTROS RECURSOS HIDRICOS','sigla'=>'OTRHID'],
            ['sector'=>'12','subsector'=>'4','tipo'=>'1','denominacion'=>'OTROS','sigla'=>'OTR11'],
            ['sector'=>'13','subsector'=>'0','tipo'=>'0','denominacion'=>'COMERCIO Y FINANZAS','sigla'=>'COMER'],
            ['sector'=>'13','subsector'=>'1','tipo'=>'0','denominacion'=>'COMERCIO','sigla'=>'COM'],
            ['sector'=>'13','subsector'=>'1','tipo'=>'1','denominacion'=>'ASUNTOS COMERCIALES Y LABORALES','sigla'=>'COM01'],
            ['sector'=>'13','subsector'=>'1','tipo'=>'2','denominacion'=>'DESARROLLO Y PROMOCIÒN DEL COMERCIO','sigla'=>'COM02'],
            ['sector'=>'13','subsector'=>'2','tipo'=>'0','denominacion'=>'FINANZAS','sigla'=>'FIN'],
            ['sector'=>'13','subsector'=>'2','tipo'=>'1','denominacion'=>'SUPERVISIÓN DE LA BANCA Y SEGUROS','sigla'=>'FIN01'],
            ['sector'=>'13','subsector'=>'3','tipo'=>'0','denominacion'=>'MULTIPROGRAMA COMERCIO Y FINANZAS','sigla'=>'MCOFI'],
            ['sector'=>'13','subsector'=>'3','tipo'=>'1','denominacion'=>'MULTIPROGRAMA','sigla'=>'MULT11'],
            ['sector'=>'13','subsector'=>'3','tipo'=>'2','denominacion'=>'INVESTIGACIÓN COMERCIO Y FINANZAS','sigla'=>'INVCF'],
            ['sector'=>'13','subsector'=>'4','tipo'=>'0','denominacion'=>'OTROS COMERCIO Y FINANZAS','sigla'=>'OTRCF'],
            ['sector'=>'13','subsector'=>'4','tipo'=>'1','denominacion'=>'OTROS','sigla'=>'OTR12'],
            ['sector'=>'14','subsector'=>'0','tipo'=>'0','denominacion'=>'ADMINISTRACION GENERAL','sigla'=>'AGUB'],
            ['sector'=>'14','subsector'=>'1','tipo'=>'0','denominacion'=>'ÓRGANO JUDICIAL','sigla'=>'JUD'],
            ['sector'=>'14','subsector'=>'1','tipo'=>'1','denominacion'=>'INFRAESTRUCTURA Y EQUIPAMIENTO DE APOYO','sigla'=>'JUD01'],
            ['sector'=>'14','subsector'=>'2','tipo'=>'0','denominacion'=>'ÓRGANO LEGISLATIVO','sigla'=>'LEG'],
            ['sector'=>'14','subsector'=>'2','tipo'=>'1','denominacion'=>'INFRAESTRUCTURA Y EQUIPAMIENTO DE APOYO','sigla'=>'LEG01'],
            ['sector'=>'14','subsector'=>'3','tipo'=>'0','denominacion'=>'ÓRGANO ELECTORAL','sigla'=>'OEL'],
            ['sector'=>'14','subsector'=>'3','tipo'=>'1','denominacion'=>'INFRAESTRUCTURA Y EQUIPAMIENTO DE APOYO','sigla'=>'OEL01'],
            ['sector'=>'14','subsector'=>'4','tipo'=>'0','denominacion'=>'ADMINISTRACION SUPERIOR EJECUTIVA','sigla'=>'EJE'],
            ['sector'=>'14','subsector'=>'5','tipo'=>'0','denominacion'=>'ADMINISTRACION FINANCIERA','sigla'=>'ADF'],
            ['sector'=>'14','subsector'=>'6','tipo'=>'0','denominacion'=>'RELACIONES EXTERIORES','sigla'=>'REXT'],
            ['sector'=>'14','subsector'=>'7','tipo'=>'0','denominacion'=>'INFORMACION ESTADÍSTICA Y PLANIFICACIÓN','sigla'=>'EST'],
            ['sector'=>'14','subsector'=>'8','tipo'=>'0','denominacion'=>'SERVICIOS DE PERSONAL','sigla'=>'SPER'],
            ['sector'=>'14','subsector'=>'9','tipo'=>'0','denominacion'=>'OTROS','sigla'=>'OTR13'],
            ['sector'=>'15','subsector'=>'0','tipo'=>'0','denominacion'=>'ORDEN PUBLICO Y SEGURIDAD CIUDADANA','sigla'=>'POLIC'],
            ['sector'=>'15','subsector'=>'1','tipo'=>'0','denominacion'=>'POLICIA','sigla'=>'POL'],
            ['sector'=>'15','subsector'=>'1','tipo'=>'1','denominacion'=>'SERVICIOS POLICIALES','sigla'=>'POL01'],
            ['sector'=>'15','subsector'=>'1','tipo'=>'2','denominacion'=>'ORDEN INTERNO','sigla'=>'POL02'],
            ['sector'=>'15','subsector'=>'1','tipo'=>'3','denominacion'=>'CONTROL DROGAS','sigla'=>'POL03'],
            ['sector'=>'15','subsector'=>'1','tipo'=>'4','denominacion'=>'SISTEMA PENITENCIARIO','sigla'=>'POL04'],
            ['sector'=>'15','subsector'=>'2','tipo'=>'0','denominacion'=>'INFRAESTRUCTURA Y EQUIPAMIENTO','sigla'=>'POLI'],
            ['sector'=>'15','subsector'=>'2','tipo'=>'1','denominacion'=>'INFRAESTRUCTURA DE APOYO Y EQUIPAMIENTO AL SISTEMA POLICIAL','sigla'=>'POLI01'],
            ['sector'=>'15','subsector'=>'2','tipo'=>'2','denominacion'=>'EQUIPAMIENTO DE SEGURIDAD CIUDADANA','sigla'=>'POLI02'],
            ['sector'=>'15','subsector'=>'3','tipo'=>'0','denominacion'=>'OTROS ORDEN PUBLICO Y SEGURIDAD CIUDADANA','sigla'=>'OTRPOL'],
            ['sector'=>'15','subsector'=>'3','tipo'=>'1','denominacion'=>'OTROS','sigla'=>'OTR14'],
            ['sector'=>'15','subsector'=>'3','tipo'=>'2','denominacion'=>'INVESTIGACION EN ORDEN PÚBLICO Y SEGURIDAD CIUDADANA','sigla'=>'INVOPSC'],
            ['sector'=>'16','subsector'=>'0','tipo'=>'0','denominacion'=>'DEFENSA NACIONAL','sigla'=>'DEF'],
            ['sector'=>'16','subsector'=>'1','tipo'=>'0','denominacion'=>'DEFENSA MILITAR','sigla'=>'DEFM'],
            ['sector'=>'16','subsector'=>'1','tipo'=>'1','denominacion'=>'DEFENSA NACIONAL','sigla'=>'DEFN01'],
            ['sector'=>'16','subsector'=>'1','tipo'=>'2','denominacion'=>'INFRAESTRUCTURA MILITAR','sigla'=>'DEFN02'],
            ['sector'=>'16','subsector'=>'1','tipo'=>'3','denominacion'=>'EQUIPAMIENTO MILITAR','sigla'=>'DEFN03'],
            ['sector'=>'16','subsector'=>'2','tipo'=>'0','denominacion'=>'DEFENSA CIVIL','sigla'=>'DEFC'],
            ['sector'=>'16','subsector'=>'2','tipo'=>'1','denominacion'=>'PREVENCIÓN DE DESASTRES','sigla'=>'DEFC01'],
            ['sector'=>'16','subsector'=>'2','tipo'=>'2','denominacion'=>'ATENCIÓN DE DESASTRES','sigla'=>'DEFC02'],
            ['sector'=>'16','subsector'=>'3','tipo'=>'0','denominacion'=>'OTROS DEFENSA NACIONAL','sigla'=>'OTRDN'],
            ['sector'=>'16','subsector'=>'3','tipo'=>'1','denominacion'=>'OTROS','sigla'=>'OTR15'],
            ['sector'=>'17','subsector'=>'0','tipo'=>'0','denominacion'=>'DEUDA PÚBLICA','sigla'=>'DEUDA'],
            ['sector'=>'17','subsector'=>'1','tipo'=>'0','denominacion'=>'INTERESES DE LA DEUDA PUBLICA','sigla'=>'DEU'],
            ['sector'=>'17','subsector'=>'2','tipo'=>'0','denominacion'=>'OTROS GASTOS','sigla'=>'OTR16'],
            ['sector'=>'18','subsector'=>'0','tipo'=>'0','denominacion'=>'MULTISECTORIAL','sigla'=>'MULTI'],
            ['sector'=>'18','subsector'=>'1','tipo'=>'0','denominacion'=>'ESTUDIOS PARA EL DESARROLLO','sigla'=>'DESRUR'],
            ['sector'=>'18','subsector'=>'1','tipo'=>'1','denominacion'=>'ESTUDIOS BASICOS PARA EL DESARROLLO','sigla'=>'DES01'],
            ['sector'=>'18','subsector'=>'1','tipo'=>'2','denominacion'=>'PROGRAMAS DE DESARROLLO RURAL SOSTENIBLE','sigla'=>'DES02'],
            ['sector'=>'18','subsector'=>'1','tipo'=>'3','denominacion'=>'ORDENAMIENTO TERRITORIAL','sigla'=>'DES03'],
            ['sector'=>'18','subsector'=>'1','tipo'=>'4','denominacion'=>'INVESTIGACIÓN PARA EL DESARROLLO','sigla'=>'DES04'],
            ['sector'=>'18','subsector'=>'2','tipo'=>'0','denominacion'=>'MULTIPROGRAMA','sigla'=>'MPRG'],
            ['sector'=>'18','subsector'=>'2','tipo'=>'1','denominacion'=>'PROGRAMAS MULTISECTORIALES','sigla'=>'MULTSEC'],
            ['sector'=>'18','subsector'=>'2','tipo'=>'2','denominacion'=>'INVESTIGACIÓN TEMÁTICAS MULTISECORIALES','sigla'=>'INVTM'],
            ['sector'=>'18','subsector'=>'3','tipo'=>'0','denominacion'=>'FORTALECIMIENTO INSTITUCIONAL','sigla'=>'FORINST'],
            ['sector'=>'18','subsector'=>'3','tipo'=>'1','denominacion'=>'PROGRAMAS DE FORTALECIMIENTO INSTITUCIONAL','sigla'=>'FORINST01'],
            ['sector'=>'18','subsector'=>'3','tipo'=>'2','denominacion'=>'INVESTIGACIÓN EN FORTALECIMIENTO INSTITUCIONAL','sigla'=>'INVFI'],
            ['sector'=>'19','subsector'=>'0','tipo'=>'0','denominacion'=>'MEDIO AMBIENTE','sigla'=>'MEDAM'],
            ['sector'=>'19','subsector'=>'1','tipo'=>'0','denominacion'=>'CONSERVACIÓN Y PROTECCIÓN DEL MEDIO AMBIENTE','sigla'=>'CPM'],
            ['sector'=>'19','subsector'=>'1','tipo'=>'1','denominacion'=>'ESTUDIOS DE RECURSOS NATURALES','sigla'=>'CPMA01'],
            ['sector'=>'19','subsector'=>'1','tipo'=>'2','denominacion'=>'MANEJO DE PARQUES Y ÁREAS PROTEGIDAS','sigla'=>'CPMA02'],
            ['sector'=>'19','subsector'=>'1','tipo'=>'3','denominacion'=>'BIODIVERSIDAD','sigla'=>'CPMA03'],
            ['sector'=>'19','subsector'=>'1','tipo'=>'4','denominacion'=>'FORESTACIÓN','sigla'=>'CPMA04'],
            ['sector'=>'19','subsector'=>'1','tipo'=>'5','denominacion'=>'REFORESTACIÓN','sigla'=>'CPMA05'],
            ['sector'=>'19','subsector'=>'1','tipo'=>'6','denominacion'=>'CONSERVACIÓN Y CONTROL EROSIÓN DE SUELOS','sigla'=>'CPMA06'],
            ['sector'=>'19','subsector'=>'1','tipo'=>'7','denominacion'=>'REMEDIACIÓN DE PASIVOS AMBIENTALES','sigla'=>'CPMA07'],
            ['sector'=>'19','subsector'=>'1','tipo'=>'8','denominacion'=>'OTROS MEDIO AMBIENTE','sigla'=>'OTR17'],
            ['sector'=>'19','subsector'=>'1','tipo'=>'9','denominacion'=>'INVESTIGACIÓN MEDIO AMBIENTE','sigla'=>'INVMA'],
            ['sector'=>'20','subsector'=>'0','tipo'=>'0','denominacion'=>'TURISMO','sigla'=>'TURIS'],
            ['sector'=>'20','subsector'=>'1','tipo'=>'0','denominacion'=>'DESARROLLO TURISTICO','sigla'=>'TUR'],
            ['sector'=>'20','subsector'=>'1','tipo'=>'1','denominacion'=>'PROMOCION TURISTICA','sigla'=>'TUR01'],
            ['sector'=>'20','subsector'=>'1','tipo'=>'2','denominacion'=>'ACTIVIDADES TURISTICAS','sigla'=>'TUR02'],
            ['sector'=>'20','subsector'=>'1','tipo'=>'3','denominacion'=>'INFRAESTRUCTURA TURISTICA','sigla'=>'TUR03'],
            ['sector'=>'20','subsector'=>'1','tipo'=>'4','denominacion'=>'OTROS TURISMO','sigla'=>'OTR18'],
            ['sector'=>'20','subsector'=>'1','tipo'=>'5','denominacion'=>'DESARROLLO TURISMO COMUNITARIO','sigla'=>'TUR05'],
            ['sector'=>'20','subsector'=>'1','tipo'=>'6','denominacion'=>'INVESTIGACIÓN TURISMO','sigla'=>'TUR06'],
            ['sector'=>'21','subsector'=>'0','tipo'=>'0','denominacion'=>'SEGURIDAD SOCIAL','sigla'=>'SEGSOC'],
            ['sector'=>'21','subsector'=>'1','tipo'=>'0','denominacion'=>'SEGURIDAD SOCIAL CORTO PLAZO','sigla'=>'SEGC'],
            ['sector'=>'21','subsector'=>'1','tipo'=>'1','denominacion'=>'INFRAESTRUCTURA Y EQUIPAMIENTO CAJAS DE SALUD','sigla'=>'SEGC01'],
            ['sector'=>'21','subsector'=>'1','tipo'=>'2','denominacion'=>'MEJORAMIENTO Y AMPLIACIÓN DE INFRAESTRUCTURA','sigla'=>'SEGC02'],
            ['sector'=>'21','subsector'=>'1','tipo'=>'3','denominacion'=>'SEGURIDAD SOCIAL EN SALUD','sigla'=>'SEGC03'],
            ['sector'=>'21','subsector'=>'2','tipo'=>'0','denominacion'=>'SEGURIDAD SOCIAL LARGO PLAZO','sigla'=>'SEGL'],
            ['sector'=>'21','subsector'=>'2','tipo'=>'1','denominacion'=>'SISTEMA DE PENSIONES','sigla'=>'SEGL01'],
            ['sector'=>'21','subsector'=>'3','tipo'=>'0','denominacion'=>'OTROS SEGURIDAD SOCIAL','sigla'=>'OTSEG'],
            ['sector'=>'21','subsector'=>'3','tipo'=>'1','denominacion'=>'CONSTRUCCIÓN Y EQUIPAMIENTO DE ORFANATOS, HOGARES, ALBERGUES, GUARDERIAS Y SIMILARES','sigla'=>'OTSEG'],
            ['sector'=>'21','subsector'=>'3','tipo'=>'2','denominacion'=>'OTROS','sigla'=>'OTR19'],
            ['sector'=>'21','subsector'=>'4','tipo'=>'0','denominacion'=>'INVESTIGACIÓN SEGURIDAD SOCIAL','sigla'=>'INVSS'],
            ['sector'=>'21','subsector'=>'4','tipo'=>'1','denominacion'=>'INVESTIGACIÓN SEGURIDAD SOCIAL','sigla'=>'INVSS01'],
            ['sector'=>'22','subsector'=>'0','tipo'=>'0','denominacion'=>'CULTURA','sigla'=>'CULTU'],
            ['sector'=>'22','subsector'=>'1','tipo'=>'0','denominacion'=>'DESARROLLO DE LA CULTURA','sigla'=>'CUL'],
            ['sector'=>'22','subsector'=>'1','tipo'=>'1','denominacion'=>'CONSTRUCCIÓN Y EQUIPAMIENTO DE INFRAESTRUCTURA CULTURAL Y PATRIMONIAL','sigla'=>'CUL01'],
            ['sector'=>'22','subsector'=>'1','tipo'=>'2','denominacion'=>'MEJORAMIENTO Y RECUPERACIÓN DE INFRAESTRUCTURA CULTURAL Y PATRIMONIAL','sigla'=>'CUL02'],
            ['sector'=>'22','subsector'=>'1','tipo'=>'3','denominacion'=>'RECUPERACIÓN DE ACTIVOS CULTURALES Y PATRIMONIALES','sigla'=>'CUL03'],
            ['sector'=>'22','subsector'=>'1','tipo'=>'4','denominacion'=>'PROMOCIÓN CULTURAL','sigla'=>'CUL04'],
            ['sector'=>'22','subsector'=>'1','tipo'=>'5','denominacion'=>'OTROS CULTURA','sigla'=>'MULT12'],
            ['sector'=>'22','subsector'=>'1','tipo'=>'6','denominacion'=>'INVESTIGACIÓN CULTURA','sigla'=>'INVCUL'],
            ['sector'=>'23','subsector'=>'0','tipo'=>'0','denominacion'=>'JUSTICIA','sigla'=>'JUSTC'],
            ['sector'=>'23','subsector'=>'1','tipo'=>'0','denominacion'=>'JUSTICIA','sigla'=>'JUS'],
            ['sector'=>'23','subsector'=>'1','tipo'=>'1','denominacion'=>'INFRAESTRUCTURA Y EQUIPAMIENTO DEL SISTEMA DE JUSTICIA','sigla'=>'JUS01'],
            ['sector'=>'23','subsector'=>'1','tipo'=>'2','denominacion'=>'MEJORAMIENTO DE INFRAESTRUCTURA DEL SISTEMA DE JUSTICIA','sigla'=>'JUS02'],
            ['sector'=>'23','subsector'=>'1','tipo'=>'3','denominacion'=>'ADMINISTRACIÓN DE JUSTICIA','sigla'=>'JUS03'],
            ['sector'=>'23','subsector'=>'1','tipo'=>'4','denominacion'=>'SEGURIDAD JURÍDICA','sigla'=>'JUS04'],
            ['sector'=>'23','subsector'=>'1','tipo'=>'5','denominacion'=>'OTROS','sigla'=>'OTR20'],
            ['sector'=>'23','subsector'=>'1','tipo'=>'6','denominacion'=>'INVESTIGACIÓN JUSTICIA','sigla'=>'INVJUS'],
            ['sector'=>'24','subsector'=>'0','tipo'=>'0','denominacion'=>'DEPORTES','sigla'=>'DEPOR'],
            ['sector'=>'24','subsector'=>'1','tipo'=>'0','denominacion'=>'DESARROLLO DEL DEPORTE','sigla'=>'DEP'],
            ['sector'=>'24','subsector'=>'1','tipo'=>'1','denominacion'=>'PROMOCIÓN Y FORTALECIMIENTO DEPORTIVO','sigla'=>'DEP01'],
            ['sector'=>'24','subsector'=>'1','tipo'=>'2','denominacion'=>'CONSTRUCCIÓN Y EQUIPAMIENTO DE INFRAESTRUCTURA DEPORTIVA URBANA','sigla'=>'DEP02'],
            ['sector'=>'24','subsector'=>'1','tipo'=>'3','denominacion'=>'CONSTRUCCIÓN Y EQUIPAMIENTO DE INFRAESTRUCTURA DEPORTIVA RURAL','sigla'=>'DEP03'],
            ['sector'=>'24','subsector'=>'1','tipo'=>'4','denominacion'=>'ASISTENCIA TÉCNICA Y CAPACITACIÓN PARA EVENTOS DEPORTIVOS','sigla'=>'DEP04'],
            ['sector'=>'24','subsector'=>'1','tipo'=>'5','denominacion'=>'REALIZACIÓN DE EVENTOS Y COMPETENCIAS DEPORTIVAS','sigla'=>'DEP05'],
            ['sector'=>'24','subsector'=>'1','tipo'=>'6','denominacion'=>'OTROS','sigla'=>'OTRSD'],
            ['sector'=>'24','subsector'=>'1','tipo'=>'7','denominacion'=>'INVESTIGACIÓN DEPORTES','sigla'=>'INVDEP'],
            



            
        ];

        foreach ($sector as $claSec) {
			$item = (object) $claSec;
			$sect = [
				"sector" => $item->sector,
				"subsector" => $item->subsector,
                "tipo" => $item->tipo,
				"denominacion" => $item->denominacion,
				"sigla" => $item->sigla,
			];
			ClaSectorial::create($sect);
        }

    }
}
