<?php
namespace Database\Seeders;

use App\Models\FrontEnd\cofinanciadores\ClaOrganismos;

use Illuminate\Database\Seeder;

class ClaOrganismosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //

        $sector = [
            ['padre'=>'0','codigo'=>'','nombre'=>'ORGANISMOS FINANCIADORES INTERNOS','sigla'=>'OFI'],
['padre'=>'1','codigo'=>'','nombre'=>'Gobierno','sigla'=>'GOB'],
['padre'=>'2','codigo'=>'111','nombre'=>'Tesoro General de la Nación','sigla'=>'TGN'],
['padre'=>'2','codigo'=>'112','nombre'=>'Tesoro General de la Nación – Papeles','sigla'=>'TGN-P'],
['padre'=>'2','codigo'=>'113','nombre'=>'Tesoro General de la Nación – Coparticipación Tributaria','sigla'=>'TGN-CT'],
['padre'=>'2','codigo'=>'114','nombre'=>'Recursos de Contravalor','sigla'=>'RECON'],
['padre'=>'2','codigo'=>'116','nombre'=>'Tesoro General de la Nación – Fondo de Compensación Departamental','sigla'=>'TGN-FCOMP'],
['padre'=>'2','codigo'=>'117','nombre'=>'Tesoro General de la Nación – Impuesto Especial a los Hidrocarburos y sus Derivados','sigla'=>'TGN-IEHD'],
['padre'=>'2','codigo'=>'119','nombre'=>'Tesoro General de la Nación – Impuesto Directo a los Hidrocarburos','sigla'=>'TGN-IDH'],
['padre'=>'2','codigo'=>'120','nombre'=>'Tesoro General de la Nación – Impuesto a la Participación en Juegos','sigla'=>'TGN-IPJ'],
['padre'=>'2','codigo'=>'121','nombre'=>'Tesoro General de la Nación – Patentes Petroleras','sigla'=>'TGN-PPET'],
['padre'=>'2','codigo'=>'129','nombre'=>'Otros Organismos Financiadores del Gobierno','sigla'=>'OT-GOB'],
['padre'=>'1','codigo'=>'','nombre'=>'TGN Otros Ingresos','sigla'=>'TGN-OT'],
['padre'=>'13','codigo'=>'','nombre'=>'Organismos de Recursos Específicos','sigla'=>'ORG-RECESP'],
['padre'=>'14','codigo'=>'210','nombre'=>'Recursos Específicos de los Gobiernos Autónomos Municipales e Indígena Originario Campesino','sigla'=>'RECESP'],
['padre'=>'14','codigo'=>'220','nombre'=>'Regalías','sigla'=>'REG'],
['padre'=>'14','codigo'=>'230','nombre'=>'Otros Recursos Específicos','sigla'=>'OTPRO'],
['padre'=>'0','codigo'=>'','nombre'=>'ORGANISMOS FINANCIADORES EXTERNOS','sigla'=>'OFE'],
['padre'=>'18','codigo'=>'','nombre'=>'Organismos Multilaterales','sigla'=>'MULT'],
['padre'=>'19','codigo'=>'311','nombre'=>'Asociación Latinoamericana de Integración','sigla'=>'ALADI'],
['padre'=>'19','codigo'=>'312','nombre'=>'Centro Interamericano de Agricultura Tropical','sigla'=>'CIAT'],
['padre'=>'19','codigo'=>'313','nombre'=>'Comisión Económica para América Latina','sigla'=>'CEPAL'],
['padre'=>'19','codigo'=>'314','nombre'=>'Corporación Andina de Fomento','sigla'=>'CAF'],
['padre'=>'19','codigo'=>'315','nombre'=>'Fondo Andino de Reserva','sigla'=>'FAR'],
['padre'=>'19','codigo'=>'316','nombre'=>'Instituto Interamericano de Cooperación Agrícola','sigla'=>'IICA'],
['padre'=>'19','codigo'=>'317','nombre'=>'Comunidad Andina de Naciones','sigla'=>'CAN'],
['padre'=>'19','codigo'=>'318','nombre'=>'Organización de los Estados Americanos','sigla'=>'OEA'],
['padre'=>'19','codigo'=>'319','nombre'=>'Organización Latinoamericana de Energía','sigla'=>'OLADE'],
['padre'=>'19','codigo'=>'321','nombre'=>'Organización Panamericana de Salud','sigla'=>'OPS'],
['padre'=>'19','codigo'=>'322','nombre'=>'Sistema Económico Latinoamericano','sigla'=>'SELA'],
['padre'=>'19','codigo'=>'323','nombre'=>'Fondo de Desarrollo de Pueblos Indígenas de América Latina y El Caribe','sigla'=>'FPDPI'],
['padre'=>'19','codigo'=>'341','nombre'=>'Centro NN.UU. para los Asentamientos Humanos','sigla'=>'HABITAT'],
['padre'=>'19','codigo'=>'342','nombre'=>'Conferencia de las NN.UU. sobre Comercio y Desarrollo','sigla'=>'UNCTAD'],
['padre'=>'19','codigo'=>'343','nombre'=>'Departamento de Cooperación Técnica para el Desarrollo','sigla'=>'DTCD'],
['padre'=>'19','codigo'=>'344','nombre'=>'Fondo de las NN.UU. para la Infancia','sigla'=>'UNICEF'],
['padre'=>'19','codigo'=>'345','nombre'=>'Fondo NN.UU. para la Actividad en Materia de Población','sigla'=>'UNFPA'],
['padre'=>'19','codigo'=>'346','nombre'=>'Fondo Internacional de Desarrollo Agrícola','sigla'=>'FIDA'],
['padre'=>'19','codigo'=>'347','nombre'=>'Instituto de NN.UU. para Formación Profesional e Investigación','sigla'=>'UNITAR'],
['padre'=>'19','codigo'=>'348','nombre'=>'Organización de Aviación Civil Internacional','sigla'=>'OACI'],
['padre'=>'19','codigo'=>'349','nombre'=>'Organización de las NN.UU. para el Desarrollo Industrial','sigla'=>'ONUDI'],
['padre'=>'19','codigo'=>'351','nombre'=>'Organización de las NN.UU. para la Agricultura y la Alimentación','sigla'=>'FAO'],
['padre'=>'19','codigo'=>'352','nombre'=>'Organización de las NN.UU. para la Educación, Ciencia y la Cultura','sigla'=>'UNESCO'],
['padre'=>'19','codigo'=>'353','nombre'=>'Organización Internacional de Energía Atómica','sigla'=>'OIEA'],
['padre'=>'19','codigo'=>'354','nombre'=>'Organización Internacional del Trabajo','sigla'=>'OIT'],
['padre'=>'19','codigo'=>'355','nombre'=>'Organización Mundial de la Salud','sigla'=>'OMS'],
['padre'=>'19','codigo'=>'356','nombre'=>'Organización Mundial de Meteorología','sigla'=>'OMM'],
['padre'=>'19','codigo'=>'357','nombre'=>'Programa de las NN.UU. para el Desarrollo','sigla'=>'PNUD'],
['padre'=>'19','codigo'=>'358','nombre'=>'Programa de NN.UU. para el Medio Ambiente','sigla'=>'PNUMA'],
['padre'=>'19','codigo'=>'359','nombre'=>'Unión Internacional de Telecomunicaciones','sigla'=>'UIT'],
['padre'=>'19','codigo'=>'361','nombre'=>'Unión Postal Universal','sigla'=>'UPU'],
['padre'=>'19','codigo'=>'362','nombre'=>'Universidad de las Naciones Unidas','sigla'=>'UNU'],
['padre'=>'19','codigo'=>'371','nombre'=>'Unión Europea','sigla'=>'UE'],
['padre'=>'19','codigo'=>'372','nombre'=>'Consejo de Asistencia Mutua Económica','sigla'=>'CAME'],
['padre'=>'19','codigo'=>'373','nombre'=>'Organization of the Petroleum Exporting Countries','sigla'=>'OPEC'],
['padre'=>'19','codigo'=>'374','nombre'=>'Programa Mundial de Alimentos','sigla'=>'PMA'],
['padre'=>'19','codigo'=>'375','nombre'=>'Organización Internacional para las Migraciones','sigla'=>'OIM'],
['padre'=>'19','codigo'=>'376','nombre'=>'Fondo de NNUU para el Desarrollo y la Capitalización','sigla'=>'FNUDC'],
['padre'=>'19','codigo'=>'377','nombre'=>'Programa de las NNUU para la Fiscalización Internacional de Drogas','sigla'=>'UNDCP'],
['padre'=>'19','codigo'=>'378','nombre'=>'Fondo de las NNUU para el Desarrollo de la Mujer','sigla'=>'UNIFEM'],
['padre'=>'19','codigo'=>'379','nombre'=>'Fondo Rotativo de las NNUU para la Exploración de Recursos Naturales','sigla'=>'UNRFNRE'],
['padre'=>'19','codigo'=>'384','nombre'=>'Fondo Nórdico para el Desarrollo','sigla'=>'NFD'],
['padre'=>'19','codigo'=>'386','nombre'=>'Organización Internacional de Maderas Tropicales','sigla'=>'OIMT'],
['padre'=>'19','codigo'=>'411','nombre'=>'Banco Interamericano de Desarrollo','sigla'=>'BID'],
['padre'=>'19','codigo'=>'412','nombre'=>'Banco Internacional de Reconstrucción y Fomento','sigla'=>'BIRF'],
['padre'=>'19','codigo'=>'413','nombre'=>'Fondo Financiero para el Desarrollo de la Cuenca del Plata','sigla'=>'FONPLATA'],
['padre'=>'19','codigo'=>'414','nombre'=>'Fondo Monetario Internacional','sigla'=>'FMI'],
['padre'=>'19','codigo'=>'415','nombre'=>'Agencia Internacional de Fomento (BM)','sigla'=>'AIF'],
['padre'=>'19','codigo'=>'416','nombre'=>'Banco Interamericano de Ahorro – Préstamo','sigla'=>'BIAPE'],
['padre'=>'19','codigo'=>'420','nombre'=>'Corporación Financiera Internacional (BM)','sigla'=>'CFI'],
['padre'=>'19','codigo'=>'421','nombre'=>'Organismo Multilateral de Garantía de Inversiones (BM)','sigla'=>'OMGI'],
['padre'=>'19','codigo'=>'522','nombre'=>'Fondo Multilateral de Inversiones (BID)','sigla'=>'FOMIN'],
['padre'=>'19','codigo'=>'524','nombre'=>'Fondo Global del Medio Ambiente (BM)','sigla'=>'GEF'],
['padre'=>'19','codigo'=>'526','nombre'=>'Fondo Institucional de Desarrollo','sigla'=>'IDF'],
['padre'=>'19','codigo'=>'997','nombre'=>'Otros Organismos Financiadores Multilaterales','sigla'=>'OT-MUL'],
['padre'=>'18','codigo'=>'','nombre'=>'Organismos Bilaterales','sigla'=>'BILAT'],
['padre'=>'75','codigo'=>'382','nombre'=>'Fondo de Ayuda al Equipamiento (España)','sigla'=>'FAE'],
['padre'=>'75','codigo'=>'383','nombre'=>'Fondo de Integración y Desarrollo Bolivia-Argentina','sigla'=>'FIDAB'],
['padre'=>'75','codigo'=>'417','nombre'=>'Banco de Importaciones - Exportaciones Japón','sigla'=>'EXIMBANK-J'],
['padre'=>'75','codigo'=>'418','nombre'=>'Banco de Importaciones - Exportaciones Corea','sigla'=>'EXIMBANK-K'],
['padre'=>'75','codigo'=>'419','nombre'=>'Banco de Importaciones - Exportaciones (EE. UU.)','sigla'=>'EXIMBANK-U'],
['padre'=>'75','codigo'=>'511','nombre'=>'Agencia Canadiense para el Desarrollo Internacional','sigla'=>'ACDI'],
['padre'=>'75','codigo'=>'512','nombre'=>'Agencia de Cooperación Internacional del Japón','sigla'=>'JICA'],
['padre'=>'75','codigo'=>'513','nombre'=>'Agencia de los EE.UU. para el Desarrollo','sigla'=>'USAID'],
['padre'=>'75','codigo'=>'514','nombre'=>'Asistencia Internacional Danesa para el Desarrollo','sigla'=>'DANIDA'],
['padre'=>'75','codigo'=>'515','nombre'=>'Agencia Suiza para el Desarrollo y la Cooperación','sigla'=>'COSUDE'],
['padre'=>'75','codigo'=>'516','nombre'=>'Instituto Alemán de Crédito para la Reconstrucción','sigla'=>'KFW'],
['padre'=>'75','codigo'=>'517','nombre'=>'Agencia de Cooperación Técnica de la República Alemana','sigla'=>'GIZ'],
['padre'=>'75','codigo'=>'518','nombre'=>'Banco de Cooperación Internacional del Japón','sigla'=>'JBIC'],
['padre'=>'75','codigo'=>'519','nombre'=>'Dir. General de Cooperación Internacional /Coop. Técnica Belga','sigla'=>'DGCI -CTB'],
['padre'=>'75','codigo'=>'520','nombre'=>'Agencia Sueca para el Desarrollo Internacional','sigla'=>'ASDI'],
['padre'=>'75','codigo'=>'521','nombre'=>'Corporación Internacional de Desarrollo','sigla'=>'CID'],
['padre'=>'75','codigo'=>'523','nombre'=>'Agencia Canadiense para el Desarrollo Internacional Regional','sigla'=>'CIID'],
['padre'=>'75','codigo'=>'525','nombre'=>'Instituto de Cooperación Iberoamericana','sigla'=>'ICI'],
['padre'=>'75','codigo'=>'527','nombre'=>'Agencia Noruega para el Desarrollo Internacional','sigla'=>'NORAD'],
['padre'=>'75','codigo'=>'528','nombre'=>'Agencia Española de Cooperación Internacional','sigla'=>'AECID'],
['padre'=>'75','codigo'=>'529','nombre'=>'Corporación de Créditos de Mercaderías (EE.UU.)','sigla'=>'CCC'],
['padre'=>'75','codigo'=>'530','nombre'=>'Export Development Corporation (CANADA)','sigla'=>'EDC'],
['padre'=>'75','codigo'=>'998','nombre'=>'Otros Organismos Financiadores Bilaterales','sigla'=>'OT-BIL'],
['padre'=>'18','codigo'=>'','nombre'=>'Gobiernos Extranjeros','sigla'=>'GOB.EXT'],
['padre'=>'99','codigo'=>'541','nombre'=>'República Federal de Alemania','sigla'=>'ALEM'],
['padre'=>'99','codigo'=>'542','nombre'=>'Argentina','sigla'=>'ARG'],
['padre'=>'99','codigo'=>'543','nombre'=>'Bélgica','sigla'=>'BEL'],
['padre'=>'99','codigo'=>'544','nombre'=>'Brasil','sigla'=>'BRA'],
['padre'=>'99','codigo'=>'545','nombre'=>'Canadá','sigla'=>'CANADA'],
['padre'=>'99','codigo'=>'546','nombre'=>'República de Corea','sigla'=>'COR'],
['padre'=>'99','codigo'=>'548','nombre'=>'República Popular China','sigla'=>'CHINA'],
['padre'=>'99','codigo'=>'549','nombre'=>'República China Nacionalista - Taiwán','sigla'=>'CH-TAI'],
['padre'=>'99','codigo'=>'551','nombre'=>'Dinamarca','sigla'=>'DIN'],
['padre'=>'99','codigo'=>'552','nombre'=>'España','sigla'=>'ESP'],
['padre'=>'99','codigo'=>'553','nombre'=>'Estados Unidos de América','sigla'=>'USA'],
['padre'=>'99','codigo'=>'554','nombre'=>'Francia','sigla'=>'FRA'],
['padre'=>'99','codigo'=>'555','nombre'=>'Gran Bretaña','sigla'=>'G-BR'],
['padre'=>'99','codigo'=>'556','nombre'=>'Holanda','sigla'=>'HOL'],
['padre'=>'99','codigo'=>'557','nombre'=>'Hungría','sigla'=>'HUN'],
['padre'=>'99','codigo'=>'558','nombre'=>'Israel','sigla'=>'ISR'],
['padre'=>'99','codigo'=>'559','nombre'=>'Italia','sigla'=>'ITA'],
['padre'=>'99','codigo'=>'561','nombre'=>'Japón','sigla'=>'JAP'],
['padre'=>'99','codigo'=>'562','nombre'=>'Noruega','sigla'=>'NOR'],
['padre'=>'99','codigo'=>'563','nombre'=>'Perú','sigla'=>'PERU'],
['padre'=>'99','codigo'=>'564','nombre'=>'Rumania','sigla'=>'RUM'],
['padre'=>'99','codigo'=>'565','nombre'=>'Suecia','sigla'=>'SUE'],
['padre'=>'99','codigo'=>'566','nombre'=>'Suiza','sigla'=>'SUI'],
['padre'=>'99','codigo'=>'567','nombre'=>'Federación de Rusia','sigla'=>'RUSIA'],
['padre'=>'99','codigo'=>'568','nombre'=>'República Bolivariana de Venezuela','sigla'=>'VEN'],
['padre'=>'99','codigo'=>'569','nombre'=>'Polonia','sigla'=>'POL'],
['padre'=>'99','codigo'=>'571','nombre'=>'Austria','sigla'=>'AUST'],
['padre'=>'99','codigo'=>'572','nombre'=>'Sudáfrica','sigla'=>'SUDAF'],
['padre'=>'99','codigo'=>'573','nombre'=>'Panamá','sigla'=>'PAN'],
['padre'=>'99','codigo'=>'574','nombre'=>'Portugal','sigla'=>'PORT'],
['padre'=>'99','codigo'=>'575','nombre'=>'República de Chile','sigla'=>'CHI'],
['padre'=>'99','codigo'=>'576','nombre'=>'México','sigla'=>'MEX'],
['padre'=>'99','codigo'=>'577','nombre'=>'República Oriental del Uruguay','sigla'=>'URU'],
['padre'=>'99','codigo'=>'578','nombre'=>'Paraguay','sigla'=>'PARA'],
['padre'=>'99','codigo'=>'579','nombre'=>'Filipinas','sigla'=>'FILIP'],
['padre'=>'99','codigo'=>'580','nombre'=>'Colombia','sigla'=>'COL'],
['padre'=>'99','codigo'=>'581','nombre'=>'Ecuador','sigla'=>'ECU'],
['padre'=>'99','codigo'=>'582','nombre'=>'Cuba','sigla'=>'CU'],
['padre'=>'99','codigo'=>'639','nombre'=>'Otros Gobiernos Extranjeros','sigla'=>'OT-G-EXT'],
['padre'=>'18','codigo'=>'','nombre'=>'Otros Organismos Financiadores Externos','sigla'=>'OTR.EXT'],
['padre'=>'139','codigo'=>'115','nombre'=>'Donaciones – HIPC II','sigla'=>'DON-HIPC'],
['padre'=>'139','codigo'=>'641','nombre'=>'Care','sigla'=>'CARE'],
['padre'=>'139','codigo'=>'642','nombre'=>'Caritas','sigla'=>'CARITAS'],
['padre'=>'139','codigo'=>'643','nombre'=>'Plan Internacional','sigla'=>'PLAN-INTER'],
['padre'=>'139','codigo'=>'644','nombre'=>'Fundación Amigos de la Naturaleza','sigla'=>'FAN'],
['padre'=>'139','codigo'=>'669','nombre'=>'Otros Organismos no Gubernamentales','sigla'=>'OT-NOGUB'],
['padre'=>'139','codigo'=>'671','nombre'=>'Bancos Privados','sigla'=>'BAN-PRI'],
['padre'=>'139','codigo'=>'672','nombre'=>'Proveedores','sigla'=>'PROV'],
['padre'=>'139','codigo'=>'719','nombre'=>'Organismos Financiadores Externos no Determinados','sigla'=>'ND-EXT'],
['padre'=>'139','codigo'=>'720','nombre'=>'Basket Funding','sigla'=>'BASK-FUN'],
['padre'=>'139','codigo'=>'729','nombre'=>'Otros Organismos Financiadores Externos','sigla'=>'OT-EXT'],


        ];

        

        foreach ($sector as $claSec) {
			$item = (object) $claSec;
			$sect = [
				"padre" => $item->padre,
				"codigo" => $item->codigo,
                "nombre" => $item->nombre,
				"sigla" => $item->sigla,
			];
			ClaOrganismos::create($sect);
        }

    }
}
